//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.Equipment.Devices.Controller.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.Equipment.Devices.Controller.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner not available on this equipment..
        /// </summary>
        public static string AlignerNotAvailable {
            get {
                return ResourceManager.GetString("AlignerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner must be empty..
        /// </summary>
        public static string AlignerNotEmpty {
            get {
                return ResourceManager.GetString("AlignerNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner is not idle..
        /// </summary>
        public static string AlignerNotIdle {
            get {
                return ResourceManager.GetString("AlignerNotIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier must be placed correctly..
        /// </summary>
        public static string CarrierNotCorrectlyPlaced {
            get {
                return ResourceManager.GetString("CarrierNotCorrectlyPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier must be opened..
        /// </summary>
        public static string CarrierNotOpened {
            get {
                return ResourceManager.GetString("CarrierNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current job in controller is not pausable (not in executing or stopping statuses)..
        /// </summary>
        public static string CurrentJobNotPausable {
            get {
                return ResourceManager.GetString("CurrentJobNotPausable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current job in controller is not resumable (not in paused status)..
        /// </summary>
        public static string CurrentJobNotResumable {
            get {
                return ResourceManager.GetString("CurrentJobNotResumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current job in controller is not resumable (not in executing status)..
        /// </summary>
        public static string CurrentJobNotStoppable {
            get {
                return ResourceManager.GetString("CurrentJobNotStoppable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} device does not inherit from Controller..
        /// </summary>
        public static string DeviceNotController {
            get {
                return ResourceManager.GetString("DeviceNotController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not idle..
        /// </summary>
        public static string DeviceNotIdle {
            get {
                return ResourceManager.GetString("DeviceNotIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFEM not available on this equipment..
        /// </summary>
        public static string EfemNotAvailable {
            get {
                return ResourceManager.GetString("EfemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier on load port {0} must be opened..
        /// </summary>
        public static string ExpectedCarrierNotOpen {
            get {
                return ResourceManager.GetString("ExpectedCarrierNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load port {0} not available on this equipment..
        /// </summary>
        public static string ExpectedLoadPortNotAvailable {
            get {
                return ResourceManager.GetString("ExpectedLoadPortNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect device selected as load port..
        /// </summary>
        public static string IncorrectLoadPortSelected {
            get {
                return ResourceManager.GetString("IncorrectLoadPortSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect device selected as process module..
        /// </summary>
        public static string IncorrectProcessModuleSelected {
            get {
                return ResourceManager.GetString("IncorrectProcessModuleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier on load port {0} must be Docked/Undocked/Open/Close..
        /// </summary>
        public static string InvalidCarrierState {
            get {
                return ResourceManager.GetString("InvalidCarrierState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination slot must be &gt; 0..
        /// </summary>
        public static string InvalidDestinationSlot1 {
            get {
                return ResourceManager.GetString("InvalidDestinationSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination slot must be &lt; {0}..
        /// </summary>
        public static string InvalidDestinationSlot2 {
            get {
                return ResourceManager.GetString("InvalidDestinationSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect device in context: expected &apos;{0}&apos;, actual &apos;{1}&apos;..
        /// </summary>
        public static string InvalidDeviceType {
            get {
                return ResourceManager.GetString("InvalidDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping must be executed on {0}..
        /// </summary>
        public static string InvalidMapping {
            get {
                return ResourceManager.GetString("InvalidMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source slot must be &gt; 0..
        /// </summary>
        public static string InvalidSourceSlot1 {
            get {
                return ResourceManager.GetString("InvalidSourceSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source slot must be &lt; {0}..
        /// </summary>
        public static string InvalidSourceSlot2 {
            get {
                return ResourceManager.GetString("InvalidSourceSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has empty substrate..
        /// </summary>
        public static string JobHaveEmptySubstrate {
            get {
                return ResourceManager.GetString("JobHaveEmptySubstrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has no substrate..
        /// </summary>
        public static string JobHaveNoSubstrate {
            get {
                return ResourceManager.GetString("JobHaveNoSubstrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has not been specified..
        /// </summary>
        public static string JobNotSpecified {
            get {
                return ResourceManager.GetString("JobNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load port not available on this equipment..
        /// </summary>
        public static string LoadPortNotAvailable {
            get {
                return ResourceManager.GetString("LoadPortNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load port is not idle..
        /// </summary>
        public static string LoadPortNotIdle {
            get {
                return ResourceManager.GetString("LoadPortNotIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job is running in the controller..
        /// </summary>
        public static string NoJobRunning {
            get {
                return ResourceManager.GetString("NoJobRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller is not idle or executing..
        /// </summary>
        public static string NotIdleOrExecuting {
            get {
                return ResourceManager.GetString("NotIdleOrExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wafer present on process module..
        /// </summary>
        public static string ProcessModuleEmpty {
            get {
                return ResourceManager.GetString("ProcessModuleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process module must be empty..
        /// </summary>
        public static string ProcessModuleNotEmpty {
            get {
                return ResourceManager.GetString("ProcessModuleNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process module is not idle..
        /// </summary>
        public static string ProcessModuleNotIdle {
            get {
                return ResourceManager.GetString("ProcessModuleNotIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot upper arm must be empty..
        /// </summary>
        public static string RobotArm1NotEmpty {
            get {
                return ResourceManager.GetString("RobotArm1NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot upper arm is not enabled..
        /// </summary>
        public static string RobotArm1NotEnabled {
            get {
                return ResourceManager.GetString("RobotArm1NotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot lower arm must be empty..
        /// </summary>
        public static string RobotArm2NotEmpty {
            get {
                return ResourceManager.GetString("RobotArm2NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot lower arm is not enabled..
        /// </summary>
        public static string RobotArm2NotEnabled {
            get {
                return ResourceManager.GetString("RobotArm2NotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot arm is not defined..
        /// </summary>
        public static string RobotArmNotDefined {
            get {
                return ResourceManager.GetString("RobotArmNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot not available on this equipment..
        /// </summary>
        public static string RobotNotAvailable {
            get {
                return ResourceManager.GetString("RobotNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot is not idle..
        /// </summary>
        public static string RobotNotIdle {
            get {
                return ResourceManager.GetString("RobotNotIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot {0} in load port {1} cannot be used..
        /// </summary>
        public static string SlotCanNotBeUsed {
            get {
                return ResourceManager.GetString("SlotCanNotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wafer present in Slot {0}..
        /// </summary>
        public static string SlotEmpty {
            get {
                return ResourceManager.GetString("SlotEmpty", resourceCulture);
            }
        }
    }
}
