//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.EFEM.Rorze.GUI.Views.Panels.Setup.DeviceSettings.IoModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IoModuleSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IoModuleSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.EFEM.Rorze.GUI.Views.Panels.Setup.DeviceSettings.IoModule.IoModuleSetting" +
                            "sResources", typeof(IoModuleSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO module settings.
        /// </summary>
        public static string BP_IO_MODULE_SETTINGS {
            get {
                return ResourceManager.GetString("BP_IO_MODULE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure coefficient.
        /// </summary>
        public static string S_SETUP_IO_MODULE_COEF_PRESSURE {
            get {
                return ResourceManager.GetString("S_SETUP_IO_MODULE_COEF_PRESSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed coefficient.
        /// </summary>
        public static string S_SETUP_IO_MODULE_COEF_SPEED {
            get {
                return ResourceManager.GetString("S_SETUP_IO_MODULE_COEF_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure sensor available.
        /// </summary>
        public static string S_SETUP_IO_MODULE_PRESSURE_SENSOR_AVAILABLE {
            get {
                return ResourceManager.GetString("S_SETUP_IO_MODULE_PRESSURE_SENSOR_AVAILABLE", resourceCulture);
            }
        }
    }
}
