//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.GUI.Common.Views.Panels.Setup.DeviceSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeviceSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.GUI.Common.Views.Panels.Setup.DeviceSettings.DeviceSettingsResources", typeof(DeviceSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no EFEM Configuration in Stand Alone mode.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_ERROR {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization timeout.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_INIT_TIMEOUT {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_INIT_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be geater than 0.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_INIT_TIMEOUT_INVALID {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_INIT_TIMEOUT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_SECONDS {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alive bit period.
        /// </summary>
        public static string SETUP_ALIVE_BIT_PERIOD {
            get {
                return ResourceManager.GetString("SETUP_ALIVE_BIT_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer timeout.
        /// </summary>
        public static string SETUP_ANSWER_TIMEOUT {
            get {
                return ResourceManager.GetString("SETUP_ANSWER_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication settings.
        /// </summary>
        public static string SETUP_COMMUNICATION_SETTINGS {
            get {
                return ResourceManager.GetString("SETUP_COMMUNICATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicator ID.
        /// </summary>
        public static string SETUP_COMMUNICATOR_ID {
            get {
                return ResourceManager.GetString("SETUP_COMMUNICATOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation timeout.
        /// </summary>
        public static string SETUP_CONFIRMATION_TIMEOUT {
            get {
                return ResourceManager.GetString("SETUP_CONFIRMATION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection mode.
        /// </summary>
        public static string SETUP_CONNECTION_MODE {
            get {
                return ResourceManager.GetString("SETUP_CONNECTION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection retry delay.
        /// </summary>
        public static string SETUP_CONNECTION_RETRY_DELAY {
            get {
                return ResourceManager.GetString("SETUP_CONNECTION_RETRY_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout.
        /// </summary>
        public static string SETUP_CONNECTION_TIMEOUT {
            get {
                return ResourceManager.GetString("SETUP_CONNECTION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init timeout.
        /// </summary>
        public static string SETUP_INIT_TIMEOUT {
            get {
                return ResourceManager.GetString("SETUP_INIT_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        public static string SETUP_IP_ADDRESS {
            get {
                return ResourceManager.GetString("SETUP_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is simulated.
        /// </summary>
        public static string SETUP_IS_SIMULATED {
            get {
                return ResourceManager.GetString("SETUP_IS_SIMULATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of retry.
        /// </summary>
        public static string SETUP_MAX_NB_RETRY {
            get {
                return ResourceManager.GetString("SETUP_MAX_NB_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max space between words in range.
        /// </summary>
        public static string SETUP_MAX_SPACE_BETWEEN_WORDS_IN_RANGE {
            get {
                return ResourceManager.GetString("SETUP_MAX_SPACE_BETWEEN_WORDS_IN_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling period interval.
        /// </summary>
        public static string SETUP_POLLING_PERIOD_INTERVAL {
            get {
                return ResourceManager.GetString("SETUP_POLLING_PERIOD_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagsConfiguration file path.
        /// </summary>
        public static string SETUP_TAGS_CONFIG_PATH {
            get {
                return ResourceManager.GetString("SETUP_TAGS_CONFIG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port.
        /// </summary>
        public static string SETUP_TCP_PORT {
            get {
                return ResourceManager.GetString("SETUP_TCP_PORT", resourceCulture);
            }
        }
    }
}
