//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.Equipment.GUI.Views.Panels.Setup.DeviceSettings.Controller
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControllerSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.Equipment.GUI.Views.Panels.Setup.DeviceSettings.Controller.ControllerSetting" +
                            "sResources", typeof(ControllerSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Settings.
        /// </summary>
        public static string BP_CONTROLLER_SETTINGS {
            get {
                return ResourceManager.GetString("BP_CONTROLLER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close door after robot action.
        /// </summary>
        public static string CLOSE_DOOR_AFTER_ROBOT_ACTION {
            get {
                return ResourceManager.GetString("CLOSE_DOOR_AFTER_ROBOT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close load port door after pick/place robot.
        /// </summary>
        public static string CLOSE_DOOR_AFTER_ROBOT_ACTION_DESCRIPTION {
            get {
                return ResourceManager.GetString("CLOSE_DOOR_AFTER_ROBOT_ACTION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Parameters.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_DEVICE_PARAMETERS {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_DEVICE_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only upper arm to load equipment.
        /// </summary>
        public static string USE_ONLY_UPPER_ARM_TO_LOAD_EQUIPMENT {
            get {
                return ResourceManager.GetString("USE_ONLY_UPPER_ARM_TO_LOAD_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only upper arm will be used to load the equipment. Throughput will be impacted..
        /// </summary>
        public static string USE_ONLY_UPPER_ARM_TO_LOAD_EQUIPMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("USE_ONLY_UPPER_ARM_TO_LOAD_EQUIPMENT_DESCRIPTION", resourceCulture);
            }
        }
    }
}
