//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Remote.Observers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class E84Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal E84Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Remote.Observers.E84Resources", typeof(E84Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string E84_CONTINUE {
            get {
                return ResourceManager.GetString("E84_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E84 Light Curtain error.
        /// </summary>
        internal static string E84_LIGHTCURTAIN_ERROR {
            get {
                return ResourceManager.GetString("E84_LIGHTCURTAIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t obstruct the light curtain. Then validate this popup to reset ES signals. Alarm will be cleared automatically..
        /// </summary>
        internal static string E84_LIGHTCURTAIN_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("E84_LIGHTCURTAIN_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E84 Access Mode Violation.
        /// </summary>
        internal static string E84_LOAD_ACCESS_MODE_VIOLATION {
            get {
                return ResourceManager.GetString("E84_LOAD_ACCESS_MODE_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carrier has been placed while load port is in auto mode. Please remove the carrier or press continue to load the carrier..
        /// </summary>
        internal static string E84_LOAD_ACCESS_MODE_VIOLATION_MESSAGE {
            get {
                return ResourceManager.GetString("E84_LOAD_ACCESS_MODE_VIOLATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please recover AMHS failure and clear alarm conditions. Then validate this popup to reset PIO signals. Alarm will be cleared automatically..
        /// </summary>
        internal static string E84_RECOVER_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("E84_RECOVER_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset ES signal.
        /// </summary>
        internal static string E84_RESET_ES {
            get {
                return ResourceManager.GetString("E84_RESET_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset PIO.
        /// </summary>
        internal static string E84_RESET_PIO {
            get {
                return ResourceManager.GetString("E84_RESET_PIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E84 TP3 Timeout.
        /// </summary>
        internal static string E84_TP3_TIMEOUT {
            get {
                return ResourceManager.GetString("E84_TP3_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E84 TP4 Timeout.
        /// </summary>
        internal static string E84_TP4_TIMEOUT {
            get {
                return ResourceManager.GetString("E84_TP4_TIMEOUT", resourceCulture);
            }
        }
    }
}
