//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlarfBinSettings
    {
        public int Id { get; set; }
        public long AreaIntervalMax { get; set; }
        public int SquareWidth { get; set; }
    }
}
