//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Inputs = new HashSet<Input>();
            this.Outputs = new HashSet<Output>();
            this.RecipeFiles = new HashSet<RecipeFile>();
            this.Results = new HashSet<Result>();
            this.ResultAcqs = new HashSet<ResultAcq>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public System.Guid KeyForAllVersion { get; set; }
        public string Name { get; set; }
        public Nullable<int> StepId { get; set; }
        public string Comment { get; set; }
        public int ActorType { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatorUserId { get; set; }
        public int CreatorChamberId { get; set; }
        public string XmlContent { get; set; }
        public int Version { get; set; }
        public bool IsArchived { get; set; }
        public bool IsShared { get; set; }
        public bool IsTemplate { get; set; }
        public bool IsValidated { get; set; }
    
        public virtual Chamber Chamber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input> Inputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Output> Outputs { get; set; }
        public virtual Step Step { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeFile> RecipeFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultAcq> ResultAcqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
