//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultValue
    {
        public long Id { get; set; }
        public long ResultId { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public double Value { get; set; }
        public int UnitType { get; set; }
        public Nullable<int> Color { get; set; }
    
        public virtual Result Result { get; set; }
    }
}
