//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultAcqItem
    {
        public long Id { get; set; }
        public long ResultAcqId { get; set; }
        public int ResultType { get; set; }
        public string FileName { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public short Idx { get; set; }
        public int State { get; set; }
        public int InternalState { get; set; }
        public Nullable<int> Tag { get; set; }
    
        public virtual ResultAcq ResultAcq { get; set; }
    }
}
