//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADC v9 - Unity-SC.
        /// </summary>
        public static string ApplicationLabel {
            get {
                return ResourceManager.GetString("ApplicationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must by a valid email address..
        /// </summary>
        public static string ErrBadFormatMail {
            get {
                return ResourceManager.GetString("ErrBadFormatMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is incorrect..
        /// </summary>
        public static string ErrBadOldPassWord {
            get {
                return ResourceManager.GetString("ErrBadOldPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect..
        /// </summary>
        public static string ErrBadPassWord {
            get {
                return ResourceManager.GetString("ErrBadPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the new password..
        /// </summary>
        public static string ErrConfirmPassWord {
            get {
                return ResourceManager.GetString("ErrConfirmPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect..
        /// </summary>
        public static string ErrEnterMail {
            get {
                return ResourceManager.GetString("ErrEnterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new password..
        /// </summary>
        public static string ErrEnterNewPassWord {
            get {
                return ResourceManager.GetString("ErrEnterNewPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the old password..
        /// </summary>
        public static string ErrEnterOldPassWord {
            get {
                return ResourceManager.GetString("ErrEnterOldPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        public static string ErrFieldRequired {
            get {
                return ResourceManager.GetString("ErrFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the login.
        /// </summary>
        public static string ErrNoLogin {
            get {
                return ResourceManager.GetString("ErrNoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password.
        /// </summary>
        public static string ErrNoPassWord {
            get {
                return ResourceManager.GetString("ErrNoPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New and confirm passwords are different..
        /// </summary>
        public static string ErrOldNewPassWordNoMatch {
            get {
                return ResourceManager.GetString("ErrOldNewPassWordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password already exits..
        /// </summary>
        public static string ErrPassWordAlreadyUsed {
            get {
                return ResourceManager.GetString("ErrPassWordAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user.
        /// </summary>
        public static string ErrUnknownUser {
            get {
                return ResourceManager.GetString("ErrUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to remove @Firstname @Lastname from the list of users ADC. @Firstname @Lastname will no longer authorized to access the ADC program.Do you really want delete @Firstname @Lastname ?.
        /// </summary>
        public static string mesConfirmDelUser {
            get {
                return ResourceManager.GetString("mesConfirmDelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection of modules is incompatible with the creation of a meta-block.
        /// </summary>
        public static string MetaBlocIncorrect {
            get {
                return ResourceManager.GetString("MetaBlocIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save model ?.
        /// </summary>
        public static string QuerySaveModel {
            get {
                return ResourceManager.GetString("QuerySaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save recipe  ?.
        /// </summary>
        public static string QuerySaveRecipe {
            get {
                return ResourceManager.GetString("QuerySaveRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop the running ?.
        /// </summary>
        public static string QueryStop {
            get {
                return ResourceManager.GetString("QueryStop", resourceCulture);
            }
        }
    }
}
