//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.Gem.Jobs.ProcessJobs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcessJobsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessJobsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.Gem.Jobs.ProcessJobs.ProcessJobsResources", typeof(ProcessJobsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add carrier.
        /// </summary>
        internal static string PJ_CARRIER_ADD {
            get {
                return ResourceManager.GetString("PJ_CARRIER_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select carrier to add.
        /// </summary>
        internal static string PJ_CARRIER_ADD_SELECTION {
            get {
                return ResourceManager.GetString("PJ_CARRIER_ADD_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate PJ.
        /// </summary>
        internal static string PJ_DUPLICATE_PJ {
            get {
                return ResourceManager.GetString("PJ_DUPLICATE_PJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one carrier.
        /// </summary>
        internal static string PJ_ERROR_CARRIER_EMPTY {
            get {
                return ResourceManager.GetString("PJ_ERROR_CARRIER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete new job name.
        /// </summary>
        internal static string PJ_INQUIRE_ID {
            get {
                return ResourceManager.GetString("PJ_INQUIRE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process job.
        /// </summary>
        internal static string PJ_PROCESS_JOB {
            get {
                return ResourceManager.GetString("PJ_PROCESS_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process job id.
        /// </summary>
        internal static string PJ_PROCESS_JOB_ID {
            get {
                return ResourceManager.GetString("PJ_PROCESS_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process jobs.
        /// </summary>
        internal static string PJ_PROCESS_JOBS {
            get {
                return ResourceManager.GetString("PJ_PROCESS_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process start.
        /// </summary>
        internal static string PJ_PROCESS_START {
            get {
                return ResourceManager.GetString("PJ_PROCESS_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe id.
        /// </summary>
        internal static string PJ_RECIPE_ID {
            get {
                return ResourceManager.GetString("PJ_RECIPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe method.
        /// </summary>
        internal static string PJ_RECIPE_METHOD {
            get {
                return ResourceManager.GetString("PJ_RECIPE_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe variables.
        /// </summary>
        internal static string PJ_RECIPE_VARIABLES {
            get {
                return ResourceManager.GetString("PJ_RECIPE_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start PJ.
        /// </summary>
        internal static string PJ_START {
            get {
                return ResourceManager.GetString("PJ_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrate(s).
        /// </summary>
        internal static string PJ_SUBSTRATE {
            get {
                return ResourceManager.GetString("PJ_SUBSTRATE", resourceCulture);
            }
        }
    }
}
