//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.GUI.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EquipmentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquipmentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.GUI.Common.Resources.EquipmentResources", typeof(EquipmentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main O-Flat.
        /// </summary>
        public static string ALIGNTYPE_MAIN_FLATCHECK {
            get {
                return ResourceManager.GetString("ALIGNTYPE_MAIN_FLATCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub O-Flat.
        /// </summary>
        public static string ALIGNTYPE_SUB_FLATCHECK {
            get {
                return ResourceManager.GetString("ALIGNTYPE_SUB_FLATCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without check.
        /// </summary>
        public static string ALIGNTYPE_WITHOUTSUBCHECK {
            get {
                return ResourceManager.GetString("ALIGNTYPE_WITHOUTSUBCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing.
        /// </summary>
        public static string CARRIERS_ACCESSING {
            get {
                return ResourceManager.GetString("CARRIERS_ACCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier ID.
        /// </summary>
        public static string CARRIERS_CARRIER_ID {
            get {
                return ResourceManager.GetString("CARRIERS_CARRIER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier ID has to be set.
        /// </summary>
        public static string CARRIERS_CARRIER_ID_EMPTY {
            get {
                return ResourceManager.GetString("CARRIERS_CARRIER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier type.
        /// </summary>
        public static string CARRIERS_CARRIER_TYPE {
            get {
                return ResourceManager.GetString("CARRIERS_CARRIER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamped.
        /// </summary>
        public static string CARRIERS_CLAMPED {
            get {
                return ResourceManager.GetString("CARRIERS_CLAMPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docked.
        /// </summary>
        public static string CARRIERS_DOCKED {
            get {
                return ResourceManager.GetString("CARRIERS_DOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID is already used.
        /// </summary>
        public static string CARRIERS_ID_USED {
            get {
                return ResourceManager.GetString("CARRIERS_ID_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not mapped.
        /// </summary>
        public static string CARRIERS_NOT_MAPPED {
            get {
                return ResourceManager.GetString("CARRIERS_NOT_MAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string CARRIERS_OPEN {
            get {
                return ResourceManager.GetString("CARRIERS_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed.
        /// </summary>
        public static string CARRIERS_PLACED {
            get {
                return ResourceManager.GetString("CARRIERS_PLACED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string CARRIERS_PRESENT {
            get {
                return ResourceManager.GetString("CARRIERS_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ID.
        /// </summary>
        public static string CARRIERS_STATUS_ID {
            get {
                return ResourceManager.GetString("CARRIERS_STATUS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string EQUIPMENT_ABORT {
            get {
                return ResourceManager.GetString("EQUIPMENT_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align.
        /// </summary>
        public static string EQUIPMENT_ALIGN {
            get {
                return ResourceManager.GetString("EQUIPMENT_ALIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner.
        /// </summary>
        public static string EQUIPMENT_ALIGNER {
            get {
                return ResourceManager.GetString("EQUIPMENT_ALIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align type.
        /// </summary>
        public static string EQUIPMENT_ALIGNTYPE {
            get {
                return ResourceManager.GetString("EQUIPMENT_ALIGNTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string EQUIPMENT_ANGLE {
            get {
                return ResourceManager.GetString("EQUIPMENT_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string EQUIPMENT_ANGLE_SOURCES {
            get {
                return ResourceManager.GetString("EQUIPMENT_ANGLE_SOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated.
        /// </summary>
        public static string EQUIPMENT_ASSOCIATED {
            get {
                return ResourceManager.GetString("EQUIPMENT_ASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string EQUIPMENT_AUTO {
            get {
                return ResourceManager.GetString("EQUIPMENT_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EQUIPMENT_CANCEL {
            get {
                return ResourceManager.GetString("EQUIPMENT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier ID read failed.
        /// </summary>
        public static string EQUIPMENT_CARRIER_ID_READ_FAILED {
            get {
                return ResourceManager.GetString("EQUIPMENT_CARRIER_ID_READ_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier complete.
        /// </summary>
        public static string EQUIPMENT_CARRIERCOMPLETE {
            get {
                return ResourceManager.GetString("EQUIPMENT_CARRIERCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier stopped.
        /// </summary>
        public static string EQUIPMENT_CARRIERSTOPPED {
            get {
                return ResourceManager.GetString("EQUIPMENT_CARRIERSTOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centering.
        /// </summary>
        public static string EQUIPMENT_CENTERING {
            get {
                return ResourceManager.GetString("EQUIPMENT_CENTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller is in maintenance.
        /// </summary>
        public static string EQUIPMENT_CONTROLLER_MAINTENANCE {
            get {
                return ResourceManager.GetString("EQUIPMENT_CONTROLLER_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed.
        /// </summary>
        public static string EQUIPMENT_CURRENTMOTIONSPEED {
            get {
                return ResourceManager.GetString("EQUIPMENT_CURRENTMOTIONSPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing.
        /// </summary>
        public static string EQUIPMENT_EXECUTING {
            get {
                return ResourceManager.GetString("EQUIPMENT_EXECUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string EQUIPMENT_IDLE {
            get {
                return ResourceManager.GetString("EQUIPMENT_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID not read.
        /// </summary>
        public static string EQUIPMENT_IDNOTREAD {
            get {
                return ResourceManager.GetString("EQUIPMENT_IDNOTREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In access.
        /// </summary>
        public static string EQUIPMENT_IN_ACCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_IN_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In access.
        /// </summary>
        public static string EQUIPMENT_INACCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_INACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init.
        /// </summary>
        public static string EQUIPMENT_INIT {
            get {
                return ResourceManager.GetString("EQUIPMENT_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string EQUIPMENT_INITIALIZING {
            get {
                return ResourceManager.GetString("EQUIPMENT_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load port.
        /// </summary>
        public static string EQUIPMENT_LOADPORT {
            get {
                return ResourceManager.GetString("EQUIPMENT_LOADPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower arm wafer.
        /// </summary>
        public static string EQUIPMENT_LOWER_ARM_WAFER_ID {
            get {
                return ResourceManager.GetString("EQUIPMENT_LOWER_ARM_WAFER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string EQUIPMENT_MAINTENANCE {
            get {
                return ResourceManager.GetString("EQUIPMENT_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string EQUIPMENT_MANUAL {
            get {
                return ResourceManager.GetString("EQUIPMENT_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed setpoint (%).
        /// </summary>
        public static string EQUIPMENT_MOTIONSPEED {
            get {
                return ResourceManager.GetString("EQUIPMENT_MOTIONSPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not accessed.
        /// </summary>
        public static string EQUIPMENT_NOTACCESSED {
            get {
                return ResourceManager.GetString("EQUIPMENT_NOTACCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not associated.
        /// </summary>
        public static string EQUIPMENT_NOTASSOCIATED {
            get {
                return ResourceManager.GetString("EQUIPMENT_NOTASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not reserved.
        /// </summary>
        public static string EQUIPMENT_NOTRESERVED {
            get {
                return ResourceManager.GetString("EQUIPMENT_NOTRESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of service.
        /// </summary>
        public static string EQUIPMENT_OUTOFSERVICE {
            get {
                return ResourceManager.GetString("EQUIPMENT_OUTOFSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        public static string EQUIPMENT_PICK {
            get {
                return ResourceManager.GetString("EQUIPMENT_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string EQUIPMENT_PLACE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string EQUIPMENT_PM_ACTIVE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string EQUIPMENT_PM_ERROR {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string EQUIPMENT_PM_IDLE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string EQUIPMENT_PM_INITIALIZING {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string EQUIPMENT_PM_OFFLINE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of service.
        /// </summary>
        public static string EQUIPMENT_PM_OUTOFSERVICE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_OUTOFSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down.
        /// </summary>
        public static string EQUIPMENT_PM_SHUTTING_DOWN {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_SHUTTING_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string EQUIPMENT_PM_UNKNOWN {
            get {
                return ResourceManager.GetString("EQUIPMENT_PM_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process module.
        /// </summary>
        public static string EQUIPMENT_PROCESS_MODULE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PROCESS_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to load.
        /// </summary>
        public static string EQUIPMENT_READYTOLOAD {
            get {
                return ResourceManager.GetString("EQUIPMENT_READYTOLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to unload.
        /// </summary>
        public static string EQUIPMENT_READYTOUNLOAD {
            get {
                return ResourceManager.GetString("EQUIPMENT_READYTOUNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string EQUIPMENT_RELEASE {
            get {
                return ResourceManager.GetString("EQUIPMENT_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string EQUIPMENT_RESERVED {
            get {
                return ResourceManager.GetString("EQUIPMENT_RESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot.
        /// </summary>
        public static string EQUIPMENT_ROBOT {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROBOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string EQUIPMENT_SELECT {
            get {
                return ResourceManager.GetString("EQUIPMENT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set motion speed.
        /// </summary>
        public static string EQUIPMENT_SETMOTIONSPEED {
            get {
                return ResourceManager.GetString("EQUIPMENT_SETMOTIONSPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrate ID reader.
        /// </summary>
        public static string EQUIPMENT_SUBSTRATE_ID_READER {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATE_ID_READER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Recipes.
        /// </summary>
        public static string EQUIPMENT_SUBSTRATE_ID_READER_GET_RECIPES {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATE_ID_READER_GET_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init.
        /// </summary>
        public static string EQUIPMENT_SUBSTRATE_ID_READER_INIT {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATE_ID_READER_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string EQUIPMENT_SUBSTRATE_ID_READER_READ {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATE_ID_READER_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        public static string EQUIPMENT_SUBSTRATE_ID_READER_RECIPE_NAME {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATE_ID_READER_RECIPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrate ID.
        /// </summary>
        public static string EQUIPMENT_SUBSTRATE_ID_READER_SUBSTRATE_ID {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATE_ID_READER_SUBSTRATE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string EQUIPMENT_TRANSFER {
            get {
                return ResourceManager.GetString("EQUIPMENT_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer blocked.
        /// </summary>
        public static string EQUIPMENT_TRANSFERBLOCKED {
            get {
                return ResourceManager.GetString("EQUIPMENT_TRANSFERBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper arm wafer.
        /// </summary>
        public static string EQUIPMENT_UPPER_ARM_WAFER_ID {
            get {
                return ResourceManager.GetString("EQUIPMENT_UPPER_ARM_WAFER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed.
        /// </summary>
        public static string EQUIPMENT_VERIFICATIONFAILED {
            get {
                return ResourceManager.GetString("EQUIPMENT_VERIFICATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification OK.
        /// </summary>
        public static string EQUIPMENT_VERIFICATIONOK {
            get {
                return ResourceManager.GetString("EQUIPMENT_VERIFICATIONOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafer ID.
        /// </summary>
        public static string EQUIPMENT_WAFER_ID {
            get {
                return ResourceManager.GetString("EQUIPMENT_WAFER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material type.
        /// </summary>
        public static string EQUIPMENT_WAFER_MATERIAL_TYPE {
            get {
                return ResourceManager.GetString("EQUIPMENT_WAFER_MATERIAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string EQUIPMENT_WAFER_PRESENCE {
            get {
                return ResourceManager.GetString("EQUIPMENT_WAFER_PRESENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string EQUIPMENT_WAFER_SIZE {
            get {
                return ResourceManager.GetString("EQUIPMENT_WAFER_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for host.
        /// </summary>
        public static string EQUIPMENT_WAITINGFORHOST {
            get {
                return ResourceManager.GetString("EQUIPMENT_WAITINGFORHOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access mode.
        /// </summary>
        public static string LOADPORT_ACCESS_MODE {
            get {
                return ResourceManager.GetString("LOADPORT_ACCESS_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier type.
        /// </summary>
        public static string LOADPORT_CARRIER_TYPE {
            get {
                return ResourceManager.GetString("LOADPORT_CARRIER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string LOADPORT_RESERVATION {
            get {
                return ResourceManager.GetString("LOADPORT_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a carrier type.
        /// </summary>
        public static string LOADPORT_SELECT_CARRIER_TYPE {
            get {
                return ResourceManager.GetString("LOADPORT_SELECT_CARRIER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service status.
        /// </summary>
        public static string LOADPORT_SERVICE_STATUS {
            get {
                return ResourceManager.GetString("LOADPORT_SERVICE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string LOADPORT_TRANSFER {
            get {
                return ResourceManager.GetString("LOADPORT_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is door opened.
        /// </summary>
        public static string PM_ISDOOROPEN {
            get {
                return ResourceManager.GetString("PM_ISDOOROPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ready to load unload.
        /// </summary>
        public static string PM_ISREADYTOLOADUNLOAD {
            get {
                return ResourceManager.GetString("PM_ISREADYTOLOADUNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set access mode.
        /// </summary>
        public static string POPUP_SET_ACCESS_MODE {
            get {
                return ResourceManager.GetString("POPUP_SET_ACCESS_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set wafer presence.
        /// </summary>
        public static string POPUP_SET_WAFER_PRESENCE {
            get {
                return ResourceManager.GetString("POPUP_SET_WAFER_PRESENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Modules.
        /// </summary>
        public static string PROCESS_MODULES {
            get {
                return ResourceManager.GetString("PROCESS_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper arm.
        /// </summary>
        public static string ROBOTCARD_ARM1 {
            get {
                return ResourceManager.GetString("ROBOTCARD_ARM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower arm.
        /// </summary>
        public static string ROBOTCARD_ARM2 {
            get {
                return ResourceManager.GetString("ROBOTCARD_ARM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoherence detected between physical sensor and software memory. Please click on wafer id to set the real wafer presence.
        /// </summary>
        public static string SENSOR_INCOHERENCE_DETECTED {
            get {
                return ResourceManager.GetString("SENSOR_INCOHERENCE_DETECTED", resourceCulture);
            }
        }
    }
}
