//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.GUI.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class L10N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L10N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.GUI.Common.Resources.L10N", typeof(L10N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string BP_ABOUT {
            get {
                return ResourceManager.GetString("BP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Rights.
        /// </summary>
        public static string BP_ACCESSRIGHTS {
            get {
                return ResourceManager.GetString("BP_ACCESSRIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string BP_ALARM_ANALYSIS {
            get {
                return ResourceManager.GetString("BP_ALARM_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string BP_APP_CONFIG {
            get {
                return ResourceManager.GetString("BP_APP_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string BP_APPEARANCE {
            get {
                return ResourceManager.GetString("BP_APPEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carriers.
        /// </summary>
        public static string BP_CARRIERS {
            get {
                return ResourceManager.GetString("BP_CARRIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Traces.
        /// </summary>
        public static string BP_COMMUNICATION_VISUALIZER {
            get {
                return ResourceManager.GetString("BP_COMMUNICATION_VISUALIZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        public static string BP_COUNTERS {
            get {
                return ResourceManager.GetString("BP_COUNTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom controls.
        /// </summary>
        public static string BP_CUSTOM_CONTROLS {
            get {
                return ResourceManager.GetString("BP_CUSTOM_CONTROLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data monitoring.
        /// </summary>
        public static string BP_DATA_COLLECTION_PLANS {
            get {
                return ResourceManager.GetString("BP_DATA_COLLECTION_PLANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data table.
        /// </summary>
        public static string BP_DATA_TABLE {
            get {
                return ResourceManager.GetString("BP_DATA_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data tree.
        /// </summary>
        public static string BP_DATA_TREE {
            get {
                return ResourceManager.GetString("BP_DATA_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter maintenance mode.
        /// </summary>
        public static string BP_ENTER_MAINTENANCE_MODE {
            get {
                return ResourceManager.GetString("BP_ENTER_MAINTENANCE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode.
        /// </summary>
        public static string BP_EQUIPMENT_HANDLING {
            get {
                return ResourceManager.GetString("BP_EQUIPMENT_HANDLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        public static string BP_GLOBAL_PARAM {
            get {
                return ResourceManager.GetString("BP_GLOBAL_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host communication.
        /// </summary>
        public static string BP_HOST_COMM_SETUP {
            get {
                return ResourceManager.GetString("BP_HOST_COMM_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string BP_ICONS {
            get {
                return ResourceManager.GetString("BP_ICONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string BP_JOBS {
            get {
                return ResourceManager.GetString("BP_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string BP_LOADPORTS_OVERVIEW {
            get {
                return ResourceManager.GetString("BP_LOADPORTS_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message area.
        /// </summary>
        public static string BP_MESSAGE_AREA {
            get {
                return ResourceManager.GetString("BP_MESSAGE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string BP_NAVIGATION {
            get {
                return ResourceManager.GetString("BP_NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Profile.
        /// </summary>
        public static string BP_OCR_PROFILE {
            get {
                return ResourceManager.GetString("BP_OCR_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel commands.
        /// </summary>
        public static string BP_PANEL_COMMANDS {
            get {
                return ResourceManager.GetString("BP_PANEL_COMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup.
        /// </summary>
        public static string BP_POPUP {
            get {
                return ResourceManager.GetString("BP_POPUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string BP_PROCESS {
            get {
                return ResourceManager.GetString("BP_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string BP_PROCESS_PROGRAM_CONFIG {
            get {
                return ResourceManager.GetString("BP_PROCESS_PROGRAM_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Editor.
        /// </summary>
        public static string BP_RECIPE_EDITOR {
            get {
                return ResourceManager.GetString("BP_RECIPE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Library.
        /// </summary>
        public static string BP_RECIPE_LIBRARY {
            get {
                return ResourceManager.GetString("BP_RECIPE_LIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Manager.
        /// </summary>
        public static string BP_RECIPE_MANAGER {
            get {
                return ResourceManager.GetString("BP_RECIPE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string BP_RESULTS {
            get {
                return ResourceManager.GetString("BP_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salience.
        /// </summary>
        public static string BP_SALIENCE {
            get {
                return ResourceManager.GetString("BP_SALIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Library.
        /// </summary>
        public static string BP_SCENARIO_LIBRARY {
            get {
                return ResourceManager.GetString("BP_SCENARIO_LIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Sequencer.
        /// </summary>
        public static string BP_SCENARIO_SEQUENCER {
            get {
                return ResourceManager.GetString("BP_SCENARIO_SEQUENCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string BP_SCENARIOS {
            get {
                return ResourceManager.GetString("BP_SCENARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string BP_SCENARIOS_CONFIGURATION {
            get {
                return ResourceManager.GetString("BP_SCENARIOS_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECS Live.
        /// </summary>
        public static string BP_SECS_MESSAGE {
            get {
                return ResourceManager.GetString("BP_SECS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Mode.
        /// </summary>
        public static string BP_SERVICE_MODE {
            get {
                return ResourceManager.GetString("BP_SERVICE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-Line Logs.
        /// </summary>
        public static string BP_SETUP_LOGS {
            get {
                return ResourceManager.GetString("BP_SETUP_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMN file viewer.
        /// </summary>
        public static string BP_SMN_VIEWER {
            get {
                return ResourceManager.GetString("BP_SMN_VIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Editor.
        /// </summary>
        public static string BP_STEP_EDITOR {
            get {
                return ResourceManager.GetString("BP_STEP_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string BP_SYSTEMINFO {
            get {
                return ResourceManager.GetString("BP_SYSTEMINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string BP_TOOLBOX {
            get {
                return ResourceManager.GetString("BP_TOOLBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string BP_USER_MANUAL {
            get {
                return ResourceManager.GetString("BP_USER_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafers.
        /// </summary>
        public static string BP_WAFERS {
            get {
                return ResourceManager.GetString("BP_WAFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Visualization.
        /// </summary>
        public static string BP_WEBVISU {
            get {
                return ResourceManager.GetString("BP_WEBVISU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF controls.
        /// </summary>
        public static string BP_WPF_CONTROLS {
            get {
                return ResourceManager.GetString("BP_WPF_CONTROLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CMD_CANCEL {
            get {
                return ResourceManager.GetString("CMD_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string CMD_VALIDATE {
            get {
                return ResourceManager.GetString("CMD_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string MENU_APPLICATION {
            get {
                return ResourceManager.GetString("MENU_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string MENU_CONTROLS {
            get {
                return ResourceManager.GetString("MENU_CONTROLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string MENU_DEVELOPERS {
            get {
                return ResourceManager.GetString("MENU_DEVELOPERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices settings.
        /// </summary>
        public static string MENU_DEVICES_SETTINGS {
            get {
                return ResourceManager.GetString("MENU_DEVICES_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data dictionary.
        /// </summary>
        public static string MENU_GEM_DATA_DICTIONARY {
            get {
                return ResourceManager.GetString("MENU_GEM_DATA_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string MENU_GEM_EQUIPMENT {
            get {
                return ResourceManager.GetString("MENU_GEM_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load ports.
        /// </summary>
        public static string MENU_GEM_LOADPORTS {
            get {
                return ResourceManager.GetString("MENU_GEM_LOADPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI components.
        /// </summary>
        public static string MENU_GUI_COMPONENTS {
            get {
                return ResourceManager.GetString("MENU_GUI_COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string MENU_HARDWARE {
            get {
                return ResourceManager.GetString("MENU_HARDWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string MENU_RESOURCES {
            get {
                return ResourceManager.GetString("MENU_RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor components.
        /// </summary>
        public static string MENU_VENDOR_COMPONENTS {
            get {
                return ResourceManager.GetString("MENU_VENDOR_COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation required.
        /// </summary>
        public static string POPUP_CONFIRMATION_TITLE {
            get {
                return ResourceManager.GetString("POPUP_CONFIRMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot arm is about to be extended.
        ///Do you confirm arm extension is safe?.
        /// </summary>
        public static string POPUP_ROBOT_ARM_EXTENSION_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("POPUP_ROBOT_ARM_EXTENSION_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke detected.
        /// </summary>
        public static string POPUP_SMOKE_DETECTED {
            get {
                return ResourceManager.GetString("POPUP_SMOKE_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sensor has detected smoke. The system will shut down the machine. Do you want to interrupt the emergency stop procedure?.
        /// </summary>
        public static string POPUP_SMOKE_DETECTED_OPERATOR_MESSAGE {
            get {
                return ResourceManager.GetString("POPUP_SMOKE_DETECTED_OPERATOR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string PROCESS {
            get {
                return ResourceManager.GetString("PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string ROOT_ALARMS {
            get {
                return ResourceManager.GetString("ROOT_ALARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string ROOT_ANALYSIS {
            get {
                return ResourceManager.GetString("ROOT_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ROOT_CONFIGURATION {
            get {
                return ResourceManager.GetString("ROOT_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ROOT_DATA {
            get {
                return ResourceManager.GetString("ROOT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string ROOT_DIAGNOSTICS {
            get {
                return ResourceManager.GetString("ROOT_DIAGNOSTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEM.
        /// </summary>
        public static string ROOT_GEM {
            get {
                return ResourceManager.GetString("ROOT_GEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ROOT_HELP {
            get {
                return ResourceManager.GetString("ROOT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ROOT_HISTORY {
            get {
                return ResourceManager.GetString("ROOT_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string ROOT_JOBS {
            get {
                return ResourceManager.GetString("ROOT_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string ROOT_LOGS {
            get {
                return ResourceManager.GetString("ROOT_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Operations.
        /// </summary>
        public static string ROOT_LOT_OPERATIONS {
            get {
                return ResourceManager.GetString("ROOT_LOT_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ROOT_MAIN {
            get {
                return ResourceManager.GetString("ROOT_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string ROOT_MAIN_EQUIPMENT {
            get {
                return ResourceManager.GetString("ROOT_MAIN_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string ROOT_MAIN_PRODUCTION {
            get {
                return ResourceManager.GetString("ROOT_MAIN_PRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string ROOT_MAINTENANCE {
            get {
                return ResourceManager.GetString("ROOT_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string ROOT_OPERATION {
            get {
                return ResourceManager.GetString("ROOT_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string ROOT_OPERATIONS {
            get {
                return ResourceManager.GetString("ROOT_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ROOT_OPTIONS {
            get {
                return ResourceManager.GetString("ROOT_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string ROOT_OVERVIEW {
            get {
                return ResourceManager.GetString("ROOT_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string ROOT_PROCESSING {
            get {
                return ResourceManager.GetString("ROOT_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string ROOT_RECIPES {
            get {
                return ResourceManager.GetString("ROOT_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string ROOT_RUN {
            get {
                return ResourceManager.GetString("ROOT_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ROOT_SERVICE {
            get {
                return ResourceManager.GetString("ROOT_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string ROOT_SETUP {
            get {
                return ResourceManager.GetString("ROOT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ROOT_STATUS {
            get {
                return ResourceManager.GetString("ROOT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ROOT_SYSTEM {
            get {
                return ResourceManager.GetString("ROOT_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the rorze application before restarting..
        /// </summary>
        public static string RORZE_SOFT_ERROR {
            get {
                return ResourceManager.GetString("RORZE_SOFT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in File Explorer.
        /// </summary>
        public static string SHOW_IN_FILE_EXPLORER {
            get {
                return ResourceManager.GetString("SHOW_IN_FILE_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags Spy.
        /// </summary>
        public static string TAGS_SPY {
            get {
                return ResourceManager.GetString("TAGS_SPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string TOOL_COLOR_PALETTE {
            get {
                return ResourceManager.GetString("TOOL_COLOR_PALETTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Logs.
        /// </summary>
        public static string TOOL_COM_LOG_VISUALIZER {
            get {
                return ResourceManager.GetString("TOOL_COM_LOG_VISUALIZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Queue.
        /// </summary>
        public static string TOOL_JOB_QUEUE {
            get {
                return ResourceManager.GetString("TOOL_JOB_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifier.
        /// </summary>
        public static string TOOL_NOTIFIER {
            get {
                return ResourceManager.GetString("TOOL_NOTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Colors.
        /// </summary>
        public static string TOOL_RAPIDCOLORS {
            get {
                return ResourceManager.GetString("TOOL_RAPIDCOLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Comparer.
        /// </summary>
        public static string TOOL_STATUS_COMPARER {
            get {
                return ResourceManager.GetString("TOOL_STATUS_COMPARER", resourceCulture);
            }
        }
    }
}
