SET(CPP_FILES
  src/BaseAlgos/EdgeDetector.cpp
  src/BaseAlgos/Filters.cpp
  src/BaseAlgos/ImageOperators.cpp
  src/BaseAlgos/Registration.cpp
  src/BaseAlgos/1DSignalAnalysis.cpp
  src/BaseAlgos/2DSignalAnalysis.cpp
  src/BaseAlgos/ShapeFinder.cpp
  src/Topography/PhaseShiftingInterferometry.cpp
  src/Topography/PhaseMapping.cpp
  src/Topography/ReliabilityHistUnwrap.cpp
  src/Topography/GoldsteinUnwrap.cpp
  src/Topography/QualGuidedUnwrap.cpp
  src/HyperAccurateCircleFitter.cpp
  src/EdgeImage.cpp
  src/Wafer.cpp
  src/NotchImage.cpp
  src/WaferImageGenerator.cpp
  src/EventQueue.cpp
  src/Event.cpp
  src/Point.cpp
  src/PolarTransform.cpp
  src/SymmetryDetector.cpp
  src/PolarImageCropper.cpp
  src/Logger.cpp
  src/ImageTypeConvertor.cpp
  src/ReportingUtils.cpp
  )

SET(H_FILES
  include/BaseAlgos/EdgeDetector.hpp
  include/BaseAlgos/Filters.hpp
  include/BaseAlgos/ImageOperators.hpp
  include/BaseAlgos/Registration.hpp
  include/BaseAlgos/1DSignalAnalysis.hpp
  include/BaseAlgos/2DSignalAnalysis.hpp
  include/BaseAlgos/ShapeFinder.hpp
  include/Topography/PhaseShiftingInterferometry.hpp
  include/Topography/PhaseMapping.hpp
  include/Topography/ReliabilityHistUnwrap.hpp
  include/Topography/GoldsteinUnwrap.hpp
  include/Topography/QualGuidedUnwrap.hpp
  include/ICircleFitter.hpp
  include/HyperAccurateCircleFitter.hpp
  include/EdgeImage.hpp
  include/NamedType.hpp
  include/Wafer.hpp
  include/Status.hpp
  include/NotchImage.hpp
  include/WaferImageGenerator.hpp
  include/Event.hpp
  include/EventHandler.hpp
  include/EventQueue.hpp
  include/Point.hpp
  include/PolarTransform.hpp
  include/SymmetryDetector.hpp
  include/Linspace.hpp
  include/PolarImageCropper.hpp
  include/Logger.hpp
  include/ImageTypeConvertor.hpp
  include/ReportingUtils.hpp
  )

SET(TESTS
  tests/test_Logger.cpp
  tests/test_ImageTypeConvertor.cpp
  tests/test_imgOperators.cpp
  tests/test_registration.cpp
  tests/test_spikeDetector.cpp
  tests/test_CircleFitter.cpp
  tests/test_EdgeImage.cpp
  tests/test_Wafer.cpp
  tests/test_NotchImage.cpp
  tests/test_WaferImageGenerator.cpp
  tests/test_EventQueue.cpp
  tests/test_Point.cpp
  tests/test_PolarTransform.cpp
  tests/test_SymmetryDetector.cpp
  tests/test_Linspace.cpp
  tests/test_PolarImageCropper.cpp
  tests/test_phaseMapping.cpp
  tests/test_phaseUnwrapping.cpp
  tests/test_shapeFinder.cpp
  )
