//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.PM.Shared.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.PM.Shared.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomDelay {
            get {
                return ResourceManager.GetString("CustomDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 Hours.
        /// </summary>
        internal static string Hours12 {
            get {
                return ResourceManager.GetString("Hours12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 10 Minutes.
        /// </summary>
        internal static string Minutes10 {
            get {
                return ResourceManager.GetString("Minutes10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 15 Minutes.
        /// </summary>
        internal static string Minutes15 {
            get {
                return ResourceManager.GetString("Minutes15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 20 Minutes.
        /// </summary>
        internal static string Minutes20 {
            get {
                return ResourceManager.GetString("Minutes20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 30 Minutes.
        /// </summary>
        internal static string Minutes30 {
            get {
                return ResourceManager.GetString("Minutes30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 5 Minutes.
        /// </summary>
        internal static string Minutes5 {
            get {
                return ResourceManager.GetString("Minutes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When occured.
        /// </summary>
        internal static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 10 Seconds.
        /// </summary>
        internal static string Seconds10 {
            get {
                return ResourceManager.GetString("Seconds10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 30 Seconds.
        /// </summary>
        internal static string Seconds30 {
            get {
                return ResourceManager.GetString("Seconds30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
