//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.Gem.DataDictionary.Alarms
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class E30AlarmPanelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal E30AlarmPanelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.Gem.DataDictionary.Alarms.E30AlarmPanelResources", typeof(E30AlarmPanelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear CEID.
        /// </summary>
        internal static string GEMPANELS_ALARM_CLEAR_CEID {
            get {
                return ResourceManager.GetString("GEMPANELS_ALARM_CLEAR_CEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string GEMPANELS_ALARM_ENABLED {
            get {
                return ResourceManager.GetString("GEMPANELS_ALARM_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set CEID.
        /// </summary>
        internal static string GEMPANELS_ALARM_SET_CEID {
            get {
                return ResourceManager.GetString("GEMPANELS_ALARM_SET_CEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string GEMPANELS_ALARM_STATE {
            get {
                return ResourceManager.GetString("GEMPANELS_ALARM_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string GEMPANELS_ALARM_TEXT {
            get {
                return ResourceManager.GetString("GEMPANELS_ALARM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        internal static string GEMPANELS_ALARMS {
            get {
                return ResourceManager.GetString("GEMPANELS_ALARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Alarm.
        /// </summary>
        internal static string GEMPANELS_CLEAR_ALARM {
            get {
                return ResourceManager.GetString("GEMPANELS_CLEAR_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Alarm.
        /// </summary>
        internal static string GEMPANELS_SET_ALARM {
            get {
                return ResourceManager.GetString("GEMPANELS_SET_ALARM", resourceCulture);
            }
        }
    }
}
