//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.Equipment.Abstractions.Devices.Efem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.Equipment.Abstractions.Devices.Efem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot device not found in EFEM..
        /// </summary>
        public static string ChildRobotNotFound {
            get {
                return ResourceManager.GetString("ChildRobotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} device has only one slot..
        /// </summary>
        public static string DeviceHaveOnlyOneSlot {
            get {
                return ResourceManager.GetString("DeviceHaveOnlyOneSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} device do not inherit from Efem..
        /// </summary>
        public static string DeviceNotAnEfem {
            get {
                return ResourceManager.GetString("DeviceNotAnEfem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} device is not expected..
        /// </summary>
        public static string DeviceNotExpected {
            get {
                return ResourceManager.GetString("DeviceNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} device is not served by robot..
        /// </summary>
        public static string DeviceNotServedByRobot {
            get {
                return ResourceManager.GetString("DeviceNotServedByRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is accessed by the robot..
        /// </summary>
        public static string LocationAccessByRobot {
            get {
                return ResourceManager.GetString("LocationAccessByRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot has not been initialized..
        /// </summary>
        public static string RobotNotInitialized {
            get {
                return ResourceManager.GetString("RobotNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot {0} is not in range [1..{1}]..
        /// </summary>
        public static string SlotNotInRange {
            get {
                return ResourceManager.GetString("SlotNotInRange", resourceCulture);
            }
        }
    }
}
