//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.Production.Equipment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductionEquipmentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductionEquipmentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.Production.Equipment.ProductionEquipmentResou" +
                            "rces", typeof(ProductionEquipmentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current activity step.
        /// </summary>
        internal static string CONTROLLER_CURRENT_ACTIVITY_STEP {
            get {
                return ResourceManager.GetString("CONTROLLER_CURRENT_ACTIVITY_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput (wafer/h).
        /// </summary>
        internal static string CONTROLLER_THROUGHPUT {
            get {
                return ResourceManager.GetString("CONTROLLER_THROUGHPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition.
        /// </summary>
        internal static string DEMETER_ACQUISITION {
            get {
                return ResourceManager.GetString("DEMETER_ACQUISITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        internal static string DEMETER_CALCULATION {
            get {
                return ResourceManager.GetString("DEMETER_CALCULATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step.
        /// </summary>
        internal static string EQUIPMENT_CURRENTSTEP {
            get {
                return ResourceManager.GetString("EQUIPMENT_CURRENTSTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        internal static string EQUIPMENT_DESELECT_ALL {
            get {
                return ResourceManager.GetString("EQUIPMENT_DESELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door status.
        /// </summary>
        internal static string EQUIPMENT_DOORSTATUS {
            get {
                return ResourceManager.GetString("EQUIPMENT_DOORSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string EQUIPMENT_ENDTIME {
            get {
                return ResourceManager.GetString("EQUIPMENT_ENDTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General informations.
        /// </summary>
        internal static string EQUIPMENT_GENERALINFORMATIONS {
            get {
                return ResourceManager.GetString("EQUIPMENT_GENERALINFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        internal static string EQUIPMENT_GENERALINFORMATIONS_EQPNAME {
            get {
                return ResourceManager.GetString("EQUIPMENT_GENERALINFORMATIONS_EQPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Selection.
        /// </summary>
        internal static string EQUIPMENT_JOB_RECIPE_SELECTION {
            get {
                return ResourceManager.GetString("EQUIPMENT_JOB_RECIPE_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafer Selection.
        /// </summary>
        internal static string EQUIPMENT_JOB_WAFER_SELECTION {
            get {
                return ResourceManager.GetString("EQUIPMENT_JOB_WAFER_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job creation in progress.
        /// </summary>
        internal static string EQUIPMENT_JOBINPROGRESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_JOBINPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job queue.
        /// </summary>
        internal static string EQUIPMENT_JOBQUEUE {
            get {
                return ResourceManager.GetString("EQUIPMENT_JOBQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a carrier on the load port.
        /// </summary>
        internal static string EQUIPMENT_LOAD_PORT_EMPTY {
            get {
                return ResourceManager.GetString("EQUIPMENT_LOAD_PORT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EQUIPMENT_NAME {
            get {
                return ResourceManager.GetString("EQUIPMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Profile.
        /// </summary>
        internal static string EQUIPMENT_OCR_PROFILE {
            get {
                return ResourceManager.GetString("EQUIPMENT_OCR_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR reading.
        /// </summary>
        internal static string EQUIPMENT_OCR_READING {
            get {
                return ResourceManager.GetString("EQUIPMENT_OCR_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string EQUIPMENT_PLACE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Process.
        /// </summary>
        internal static string EQUIPMENT_POST_PROCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_POST_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-process.
        /// </summary>
        internal static string EQUIPMENT_PRE_PROCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_PRE_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string EQUIPMENT_PRESSURE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PRESSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string EQUIPMENT_PROCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process module.
        /// </summary>
        internal static string EQUIPMENT_PROCESS_MODULE {
            get {
                return ResourceManager.GetString("EQUIPMENT_PROCESS_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed substrates.
        /// </summary>
        internal static string EQUIPMENT_PROCESSEDSUBSTRATECOUNT {
            get {
                return ResourceManager.GetString("EQUIPMENT_PROCESSEDSUBSTRATECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Job ID.
        /// </summary>
        internal static string EQUIPMENT_PROCESSJOBID {
            get {
                return ResourceManager.GetString("EQUIPMENT_PROCESSJOBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression.
        /// </summary>
        internal static string EQUIPMENT_PROGRESSION {
            get {
                return ResourceManager.GetString("EQUIPMENT_PROGRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string EQUIPMENT_RECIPE {
            get {
                return ResourceManager.GetString("EQUIPMENT_RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe progression.
        /// </summary>
        internal static string EQUIPMENT_RECIPE_PROGRESSION {
            get {
                return ResourceManager.GetString("EQUIPMENT_RECIPE_PROGRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string EQUIPMENT_SELECT_ALL {
            get {
                return ResourceManager.GetString("EQUIPMENT_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source location.
        /// </summary>
        internal static string EQUIPMENT_SOURCELOCATION {
            get {
                return ResourceManager.GetString("EQUIPMENT_SOURCELOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string EQUIPMENT_STARTTIME {
            get {
                return ResourceManager.GetString("EQUIPMENT_STARTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string EQUIPMENT_STATE {
            get {
                return ResourceManager.GetString("EQUIPMENT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string EQUIPMENT_STATUS {
            get {
                return ResourceManager.GetString("EQUIPMENT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafers ID.
        /// </summary>
        internal static string EQUIPMENT_SUBSTRATE_ID {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafers.
        /// </summary>
        internal static string EQUIPMENT_SUBSTRATES_SLOTMAP {
            get {
                return ResourceManager.GetString("EQUIPMENT_SUBSTRATES_SLOTMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string EQUIPMENT_TEMPERATURE {
            get {
                return ResourceManager.GetString("EQUIPMENT_TEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafer Id.
        /// </summary>
        internal static string EQUIPMENT_WAFER_ID {
            get {
                return ResourceManager.GetString("EQUIPMENT_WAFER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafers.
        /// </summary>
        internal static string EQUIPMENT_WAFERS {
            get {
                return ResourceManager.GetString("EQUIPMENT_WAFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load port.
        /// </summary>
        internal static string LOAD_PORT {
            get {
                return ResourceManager.GetString("LOAD_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort recipe.
        /// </summary>
        internal static string PM_ABORT_RECIPE {
            get {
                return ResourceManager.GetString("PM_ABORT_RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string RECIPE {
            get {
                return ResourceManager.GetString("RECIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
    }
}
