//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.GUI.Common.Views.Panels.Sample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SamplePanelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SamplePanelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.GUI.Common.Views.Panels.Sample.SamplePanelResources", typeof(SamplePanelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string BP_SAMPLE {
            get {
                return ResourceManager.GetString("BP_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Cmd.
        /// </summary>
        public static string BP_SAMPLE_CMD {
            get {
                return ResourceManager.GetString("BP_SAMPLE_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom message here.
        /// </summary>
        public static string BP_SAMPLE_POPUP_MESSAGE {
            get {
                return ResourceManager.GetString("BP_SAMPLE_POPUP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Sample Title.
        /// </summary>
        public static string BP_SAMPLE_POPUP_TITLE {
            get {
                return ResourceManager.GetString("BP_SAMPLE_POPUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code behind command.
        /// </summary>
        public static string CODE_BEHIND_COMMAND {
            get {
                return ResourceManager.GetString("CODE_BEHIND_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom application message here.
        /// </summary>
        public static string CUSTOM_ERROR_USER_MESSAGE {
            get {
                return ResourceManager.GetString("CUSTOM_ERROR_USER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My custom message.
        /// </summary>
        public static string CUSTOM_USER_MESSAGE {
            get {
                return ResourceManager.GetString("CUSTOM_USER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display application message.
        /// </summary>
        public static string DISPLAY_APPLICATION_MESSAGE {
            get {
                return ResourceManager.GetString("DISPLAY_APPLICATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display popup.
        /// </summary>
        public static string DISPLAY_POPUP {
            get {
                return ResourceManager.GetString("DISPLAY_POPUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show busy indicator.
        /// </summary>
        public static string DISPLAY_SHOW_BUSY_INDICATOR {
            get {
                return ResourceManager.GetString("DISPLAY_SHOW_BUSY_INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display user message.
        /// </summary>
        public static string DISPLAY_USER_MESSAGE {
            get {
                return ResourceManager.GetString("DISPLAY_USER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVVM command.
        /// </summary>
        public static string MVVM_COMMAND {
            get {
                return ResourceManager.GetString("MVVM_COMMAND", resourceCulture);
            }
        }
    }
}
