//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataFlow.ProcessModules.GUI.Views.Panels.Setup.DeviceSettings.ProcessModule.UnityProcessModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnityProcessModuleSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnityProcessModuleSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.DataFlow.ProcessModules.GUI.Views.Panels.Setup.DeviceSettings.ProcessModu" +
                            "le.UnityProcessModule.UnityProcessModuleSettingsResources", typeof(UnityProcessModuleSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of service.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_OUT_OF_SERVICE {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_OUT_OF_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF host&apos;s IP Address.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_WCF_HOST_IP_ADDRESS {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_WCF_HOST_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF host&apos;s port.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_WCF_HOST_PORT {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_WCF_HOST_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF Host port must be between 0 and 65535..
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_WCF_HOST_PORT_INVALID {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_WCF_HOST_PORT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF host&apos;s URI segment.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_WCF_HOST_URI_SEGMENT {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_WCF_HOST_URI_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF communication check retry number.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_WCF_RETRY_NUMBER {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_WCF_RETRY_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF communication check delay.
        /// </summary>
        public static string S_SETUP_DEVICE_SETTINGS_WCF_TIMEOUT {
            get {
                return ResourceManager.GetString("S_SETUP_DEVICE_SETTINGS_WCF_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Module Settings.
        /// </summary>
        public static string S_SETUP_PROCESS_MODULE_SETTINGS {
            get {
                return ResourceManager.GetString("S_SETUP_PROCESS_MODULE_SETTINGS", resourceCulture);
            }
        }
    }
}
