//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.Equipment.Abstractions.Devices.ProcessModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.Equipment.Abstractions.Devices.ProcessModule.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} device do not inherit from process module..
        /// </summary>
        public static string DeviceNotAProcessModule {
            get {
                return ResourceManager.GetString("DeviceNotAProcessModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door is closed.
        /// </summary>
        public static string DoorClosed {
            get {
                return ResourceManager.GetString("DoorClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM{0} is not supported.
        /// </summary>
        public static string InstanceNotSupported {
            get {
                return ResourceManager.GetString("InstanceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process module is out of service.
        /// </summary>
        public static string IsOutOfService {
            get {
                return ResourceManager.GetString("IsOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready to load/unload.
        /// </summary>
        public static string NotReadyToLoadUnload {
            get {
                return ResourceManager.GetString("NotReadyToLoadUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process module has only one slot.
        /// </summary>
        public static string ProcessModuleHaveOnlyOneSlot {
            get {
                return ResourceManager.GetString("ProcessModuleHaveOnlyOneSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrate detection is in error.
        /// </summary>
        public static string SubstrateDetectionError {
            get {
                return ResourceManager.GetString("SubstrateDetectionError", resourceCulture);
            }
        }
    }
}
