//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.EFEM.Brooks.GUI.Views.Panels.Setup.DeviceSettings.Robot.BrooksRobot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrooksRobotSettingsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrooksRobotSettingsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.EFEM.Brooks.GUI.Views.Panels.Setup.DeviceSettings.Robot.BrooksRobot.Brook" +
                            "sRobotSettingsResource", typeof(BrooksRobotSettingsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks robot name.
        /// </summary>
        public static string BROOKS_ROBOT_NAME {
            get {
                return ResourceManager.GetString("BROOKS_ROBOT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower arm name.
        /// </summary>
        public static string LOWER_ARM_NAME {
            get {
                return ResourceManager.GetString("LOWER_ARM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower end effector name.
        /// </summary>
        public static string LOWER_END_EFFECTOR_NAME {
            get {
                return ResourceManager.GetString("LOWER_END_EFFECTOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sample dimension to add.
        /// </summary>
        public static string ROBOT_ADD_SAMPLE_DIMENSION {
            get {
                return ResourceManager.GetString("ROBOT_ADD_SAMPLE_DIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select transfer location to add.
        /// </summary>
        public static string ROBOT_ADD_TRANSFER_LOCATION {
            get {
                return ResourceManager.GetString("ROBOT_ADD_TRANSFER_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit stopping position.
        /// </summary>
        public static string ROBOT_EDIT_STOPPING_POSITION {
            get {
                return ResourceManager.GetString("ROBOT_EDIT_STOPPING_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot home motion profile.
        /// </summary>
        public static string ROBOT_HOME_MOTION_PROFILE {
            get {
                return ResourceManager.GetString("ROBOT_HOME_MOTION_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position X axis.
        /// </summary>
        public static string ROBOT_POSITION_X {
            get {
                return ResourceManager.GetString("ROBOT_POSITION_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis:.
        /// </summary>
        public static string ROBOT_POSITION_X_TEXT {
            get {
                return ResourceManager.GetString("ROBOT_POSITION_X_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stop position defined.
        /// </summary>
        public static string STOPPING_POSITIONS_ERROR_EMPTY {
            get {
                return ResourceManager.GetString("STOPPING_POSITIONS_ERROR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All transfer locations must have arm stopping position defined.
        /// </summary>
        public static string STOPPING_POSITIONS_ERROR_STOPPING_POSITION_EMPTY {
            get {
                return ResourceManager.GetString("STOPPING_POSITIONS_ERROR_STOPPING_POSITION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sample dimensions must have transfer location defined.
        /// </summary>
        public static string STOPPING_POSITIONS_ERROR_TRANSFER_LOCATION_EMPTY {
            get {
                return ResourceManager.GetString("STOPPING_POSITIONS_ERROR_TRANSFER_LOCATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper arm name.
        /// </summary>
        public static string UPPER_ARM_NAME {
            get {
                return ResourceManager.GetString("UPPER_ARM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper end effector name.
        /// </summary>
        public static string UPPER_END_EFFECTOR_NAME {
            get {
                return ResourceManager.GetString("UPPER_END_EFFECTOR_NAME", resourceCulture);
            }
        }
    }
}
