namespace UnitySC.EFEM.Rorze.Devices.LoadPort.RV201.Driver.Enums
{
    public enum SystemDataProperty
    {
        LPUSerialNo                             = 0,
        HostIpaddress                           = 1,
        Rs232cSetting                           = 2,
        BodyNumber                              = 6,
        EventEnablingFlag                       = 7,
        SoftwareSwitch                          = 8,
        SoftwareSwitch2                         = 9,
        EmergencyStopSignal                     = 10,
        TemporarilyStopSignal                   = 11,
        VacuumSourcePressureSignal              = 12,
        AirSourcePressureSignal                 = 13,
        YaxisOsAfterChuckingOff                 = 14,
        OperatingTimeOfCarrierClamp             = 15,
        OperatingTimeDoorLockKey                = 16,
        OperatingTimeMappingSensor              = 17,
        DoorChuckingTime                        = 18,
        YaxisOsShortUndock                      = 19,
        WaitWhenStartingMapping                 = 20,
        YaxisOaShortUndock                      = 21,
        OperatingTimeLiftingLowering            = 22,
        OperatingTimeCarrierRetainer            = 23,
        PlacementSensorChatteringPreventingTime = 24,
        CarrierDetectingTime                    = 25,
        YaxisMotionPulse                        = 26,
        IndicatorAutomaticOutputSetting         = 27,
        WaferPushingInPosition                  = 28,
        InputDelayTimeMappingSensor             = 29,
        YaxisOsShortDock                        = 30,
        CoverLockingTimeInterval                = 31,
        SignalOutputSetting                     = 32,
        StatusSetting                           = 38,
        SystemType                              = 39,
        IndicatorAssignmentbit0                 = 40,
        IndicatorAssignmentbit1                 = 41,
        IndicatorAssignmentbit2                 = 42,
        IndicatorAssignmentbit3                 = 43,
        IndicatorAssignmentbit4                 = 44,
        IndicatorAssignmentbit5                 = 45,
        IndicatorAssignmentbit6                 = 46,
        IndicatorAssignmentbit7                 = 47,
        IndicatorAssignmentbit8                 = 48,
        IndicatorAssignmentbit9                 = 49,
        TCPportNumber                           = 68,
        LogServerIPaddress                      = 69
    }
}
