//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.PM.DMT.CommonUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.PM.DMT.CommonUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude X.
        /// </summary>
        public static string DMT_AmplitudeX_Back {
            get {
                return ResourceManager.GetString("DMT_AmplitudeX_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude X.
        /// </summary>
        public static string DMT_AmplitudeX_Front {
            get {
                return ResourceManager.GetString("DMT_AmplitudeX_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude Y.
        /// </summary>
        public static string DMT_AmplitudeY_Back {
            get {
                return ResourceManager.GetString("DMT_AmplitudeY_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude Y.
        /// </summary>
        public static string DMT_AmplitudeY_Front {
            get {
                return ResourceManager.GetString("DMT_AmplitudeY_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright-field.
        /// </summary>
        public static string DMT_Brightfield_Back {
            get {
                return ResourceManager.GetString("DMT_Brightfield_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright-field.
        /// </summary>
        public static string DMT_Brightfield_Front {
            get {
                return ResourceManager.GetString("DMT_Brightfield_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curvature X.
        /// </summary>
        public static string DMT_CurvatureX_Back {
            get {
                return ResourceManager.GetString("DMT_CurvatureX_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curvature X.
        /// </summary>
        public static string DMT_CurvatureX_Front {
            get {
                return ResourceManager.GetString("DMT_CurvatureX_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curvature Y.
        /// </summary>
        public static string DMT_CurvatureY_Back {
            get {
                return ResourceManager.GetString("DMT_CurvatureY_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curvature Y.
        /// </summary>
        public static string DMT_CurvatureY_Front {
            get {
                return ResourceManager.GetString("DMT_CurvatureY_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low angle dark-field.
        /// </summary>
        public static string DMT_Dark_Back {
            get {
                return ResourceManager.GetString("DMT_Dark_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low angle dark-field.
        /// </summary>
        public static string DMT_Dark_Front {
            get {
                return ResourceManager.GetString("DMT_Dark_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High angle dark-field.
        /// </summary>
        public static string DMT_ObliqueLight_Back {
            get {
                return ResourceManager.GetString("DMT_ObliqueLight_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High angle dark-field.
        /// </summary>
        public static string DMT_ObliqueLight_Front {
            get {
                return ResourceManager.GetString("DMT_ObliqueLight_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase mask.
        /// </summary>
        public static string DMT_PhaseMask_Back {
            get {
                return ResourceManager.GetString("DMT_PhaseMask_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase mask.
        /// </summary>
        public static string DMT_PhaseMask_Front {
            get {
                return ResourceManager.GetString("DMT_PhaseMask_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight.
        /// </summary>
        public static string DMT_TopoBackLight_Back {
            get {
                return ResourceManager.GetString("DMT_TopoBackLight_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight.
        /// </summary>
        public static string DMT_TopoBackLight_Front {
            get {
                return ResourceManager.GetString("DMT_TopoBackLight_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo normals X.
        /// </summary>
        public static string DMT_TopoPhaseNX_Back {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseNX_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo normals X.
        /// </summary>
        public static string DMT_TopoPhaseNX_Front {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseNX_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo normals Y.
        /// </summary>
        public static string DMT_TopoPhaseNY_Back {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseNY_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo normals Y.
        /// </summary>
        public static string DMT_TopoPhaseNY_Front {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseNY_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo normals Z.
        /// </summary>
        public static string DMT_TopoPhaseNZ_Back {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseNZ_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo normals Z.
        /// </summary>
        public static string DMT_TopoPhaseNZ_Front {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseNZ_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo X coordinates.
        /// </summary>
        public static string DMT_TopoPhaseX_Back {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseX_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo X coordinates.
        /// </summary>
        public static string DMT_TopoPhaseX_Front {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseX_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo Y coordinates.
        /// </summary>
        public static string DMT_TopoPhaseY_Back {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseY_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo Y coordinates.
        /// </summary>
        public static string DMT_TopoPhaseY_Front {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseY_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo height map.
        /// </summary>
        public static string DMT_TopoPhaseZ_Back {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseZ_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalTopo height map.
        /// </summary>
        public static string DMT_TopoPhaseZ_Front {
            get {
                return ResourceManager.GetString("DMT_TopoPhaseZ_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope map X.
        /// </summary>
        public static string DMT_UnwrappedPhaseX_Back {
            get {
                return ResourceManager.GetString("DMT_UnwrappedPhaseX_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope map X.
        /// </summary>
        public static string DMT_UnwrappedPhaseX_Front {
            get {
                return ResourceManager.GetString("DMT_UnwrappedPhaseX_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope map Y.
        /// </summary>
        public static string DMT_UnwrappedPhaseY_Back {
            get {
                return ResourceManager.GetString("DMT_UnwrappedPhaseY_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope map Y.
        /// </summary>
        public static string DMT_UnwrappedPhaseY_Front {
            get {
                return ResourceManager.GetString("DMT_UnwrappedPhaseY_Front", resourceCulture);
            }
        }
    }
}
