//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.EFEM.Brooks.Devices.Robot.BrooksRobot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.EFEM.Brooks.Devices.Robot.BrooksRobot.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} is not supported by condition {1}..
        /// </summary>
        public static string CommandNotSupported {
            get {
                return ResourceManager.GetString("CommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not a Brooks robot.
        /// </summary>
        public static string DeviceNotABrooksRobot {
            get {
                return ResourceManager.GetString("DeviceNotABrooksRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion profiles are empty.
        /// </summary>
        public static string MotionProfilesEmpty {
            get {
                return ResourceManager.GetString("MotionProfilesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot is in maintenance.
        /// </summary>
        public static string RobotInMaintenance {
            get {
                return ResourceManager.GetString("RobotInMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot is not operable.
        /// </summary>
        public static string RobotNotOperable {
            get {
                return ResourceManager.GetString("RobotNotOperable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot not found in EFEM configuration.
        /// </summary>
        public static string RobotNotPresentInEfemConfig {
            get {
                return ResourceManager.GetString("RobotNotPresentInEfemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified motion profile is unknown.
        /// </summary>
        public static string UnknownMotionProfile {
            get {
                return ResourceManager.GetString("UnknownMotionProfile", resourceCulture);
            }
        }
    }
}
