//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Tools.TerminalMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalMessagesToolResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalMessagesToolResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Tools.TerminalMessages.TerminalMessagesToolResource", typeof(TerminalMessagesToolResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host #{0}.
        /// </summary>
        public static string TERMINAL_MESSAGE_HOST_NAME {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGE_HOST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlogged user.
        /// </summary>
        public static string TERMINAL_MESSAGE_UNLOGGED_USER {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGE_UNLOGGED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal messages.
        /// </summary>
        public static string TERMINAL_MESSAGES {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        public static string TERMINAL_MESSAGES_ACKNOWLEDGE {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGES_ACKNOWLEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        public static string TERMINAL_MESSAGES_ACKNOWLEDGED {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGES_ACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not acknowledged.
        /// </summary>
        public static string TERMINAL_MESSAGES_NOT_ACKNOWLEDGED {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGES_NOT_ACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string TERMINAL_MESSAGES_REPLY {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGES_REPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TERMINAL_MESSAGES_SEND {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGES_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy HH:mm:ss.
        /// </summary>
        public static string TERMINAL_MESSAGES_TIME_FORMAT {
            get {
                return ResourceManager.GetString("TERMINAL_MESSAGES_TIME_FORMAT", resourceCulture);
            }
        }
    }
}
