//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.Gem.Jobs.ControlJobs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlJobResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlJobResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.Gem.Jobs.ControlJobs.ControlJobResources", typeof(ControlJobResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort CJ.
        /// </summary>
        internal static string CJ_ABORT {
            get {
                return ResourceManager.GetString("CJ_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add input carrier.
        /// </summary>
        internal static string CJ_CARRIER_INPUT_ADD {
            get {
                return ResourceManager.GetString("CJ_CARRIER_INPUT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select carrier input to add.
        /// </summary>
        internal static string CJ_CARRIER_INPUT_ADD_SELECTION {
            get {
                return ResourceManager.GetString("CJ_CARRIER_INPUT_ADD_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection plan.
        /// </summary>
        internal static string CJ_COLLECTION_PLAN {
            get {
                return ResourceManager.GetString("CJ_COLLECTION_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control job.
        /// </summary>
        internal static string CJ_CONTROL_JOB {
            get {
                return ResourceManager.GetString("CJ_CONTROL_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control job id.
        /// </summary>
        internal static string CJ_CONTROL_JOB_ID {
            get {
                return ResourceManager.GetString("CJ_CONTROL_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control jobs.
        /// </summary>
        internal static string CJ_CONTROL_JOBS {
            get {
                return ResourceManager.GetString("CJ_CONTROL_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        internal static string CJ_DESELECT {
            get {
                return ResourceManager.GetString("CJ_DESELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one process job.
        /// </summary>
        internal static string CJ_ERROR_PJ_COUNT {
            get {
                return ResourceManager.GetString("CJ_ERROR_PJ_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOQ.
        /// </summary>
        internal static string CJ_HOQ {
            get {
                return ResourceManager.GetString("CJ_HOQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Out Specification.
        /// </summary>
        internal static string CJ_MTL_OUT_SPEC {
            get {
                return ResourceManager.GetString("CJ_MTL_OUT_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string CJ_MTL_OUT_SPEC_DESTINATION {
            get {
                return ResourceManager.GetString("CJ_MTL_OUT_SPEC_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string CJ_MTL_OUT_SPEC_SOURCE {
            get {
                return ResourceManager.GetString("CJ_MTL_OUT_SPEC_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control order.
        /// </summary>
        internal static string CJ_ORDER {
            get {
                return ResourceManager.GetString("CJ_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause CJ.
        /// </summary>
        internal static string CJ_PAUSE {
            get {
                return ResourceManager.GetString("CJ_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add process job.
        /// </summary>
        internal static string CJ_PROCESSJOB_ADD {
            get {
                return ResourceManager.GetString("CJ_PROCESSJOB_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a process job to add.
        /// </summary>
        internal static string CJ_PROCESSJOB_ADD_SELECTION {
            get {
                return ResourceManager.GetString("CJ_PROCESSJOB_ADD_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume CJ.
        /// </summary>
        internal static string CJ_RESUME {
            get {
                return ResourceManager.GetString("CJ_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start CJ.
        /// </summary>
        internal static string CJ_START {
            get {
                return ResourceManager.GetString("CJ_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start method.
        /// </summary>
        internal static string CJ_START_METHOD {
            get {
                return ResourceManager.GetString("CJ_START_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop CJ.
        /// </summary>
        internal static string CJ_STOP {
            get {
                return ResourceManager.GetString("CJ_STOP", resourceCulture);
            }
        }
    }
}
