//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.EquipmentHandling.Clean {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CleanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CleanResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.EquipmentHandling.Clean.CleanResources", typeof(CleanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean out.
        /// </summary>
        internal static string CLEAN {
            get {
                return ResourceManager.GetString("CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All locations must be idle to allow clean. Please initialize them.
        /// </summary>
        internal static string CLEAN_ALL_LOCATIONS_MUST_BE_IDLE {
            get {
                return ResourceManager.GetString("CLEAN_ALL_LOCATIONS_MUST_BE_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All wafers must be have a destination port and destination slot. Please select one for each wafers.
        /// </summary>
        internal static string CLEAN_ALL_SUBSTRATE_MUST_HAVE_DESTINATION {
            get {
                return ResourceManager.GetString("CLEAN_ALL_SUBSTRATE_MUST_HAVE_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All wafers must have a defined material type. Please select one..
        /// </summary>
        internal static string CLEAN_ALL_SUBSTRATE_MUST_HAVE_MATERIAL_TYPE {
            get {
                return ResourceManager.GetString("CLEAN_ALL_SUBSTRATE_MUST_HAVE_MATERIAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CLEAN_CANCEL {
            get {
                return ResourceManager.GetString("CLEAN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CLEAN_CONFIRM {
            get {
                return ResourceManager.GetString("CLEAN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string CLEAN_DESTINATION {
            get {
                return ResourceManager.GetString("CLEAN_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Port.
        /// </summary>
        internal static string CLEAN_DESTINATION_PORT {
            get {
                return ResourceManager.GetString("CLEAN_DESTINATION_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Slot.
        /// </summary>
        internal static string CLEAN_DESTINATION_SLOT {
            get {
                return ResourceManager.GetString("CLEAN_DESTINATION_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean out execution aborted : {0}.
        /// </summary>
        internal static string CLEAN_EXECUTION_ABORTED {
            get {
                return ResourceManager.GetString("CLEAN_EXECUTION_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force presence.
        /// </summary>
        internal static string CLEAN_FORCE_PRESENCE {
            get {
                return ResourceManager.GetString("CLEAN_FORCE_PRESENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force substrate presence at location &apos;{0}&apos;.
        /// </summary>
        internal static string CLEAN_FORCE_TITLE {
            get {
                return ResourceManager.GetString("CLEAN_FORCE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some slots are not available. Please change destination on involved substrates.
        /// </summary>
        internal static string CLEAN_LOAD_PORT_SLOT_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("CLEAN_LOAD_PORT_SLOT_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All used load ports for clean out sequence must be opened. Please load them in the equipment.
        /// </summary>
        internal static string CLEAN_LOAD_PORTS_MUST_BE_OPENED {
            get {
                return ResourceManager.GetString("CLEAN_LOAD_PORTS_MUST_BE_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string CLEAN_LOCATION {
            get {
                return ResourceManager.GetString("CLEAN_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical.
        /// </summary>
        internal static string CLEAN_LOGICAL {
            get {
                return ResourceManager.GetString("CLEAN_LOGICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple substrates have the same destination. Please select a new destination.
        /// </summary>
        internal static string CLEAN_MANY_SUBSTRATES_SAME_DESTINATION {
            get {
                return ResourceManager.GetString("CLEAN_MANY_SUBSTRATES_SAME_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material type.
        /// </summary>
        internal static string CLEAN_MATERIAL_TYPE {
            get {
                return ResourceManager.GetString("CLEAN_MATERIAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some substrates do not have a size.
        /// </summary>
        internal static string CLEAN_NO_SIZE_WARNING {
            get {
                return ResourceManager.GetString("CLEAN_NO_SIZE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No substrate to clean out. Please cancel the popup.
        /// </summary>
        internal static string CLEAN_NO_SUBSTRATE_TO_CLEAN {
            get {
                return ResourceManager.GetString("CLEAN_NO_SUBSTRATE_TO_CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        internal static string CLEAN_NOT_DEFINED {
            get {
                return ResourceManager.GetString("CLEAN_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string CLEAN_ORIGIN {
            get {
                return ResourceManager.GetString("CLEAN_ORIGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean out setup aborted. Could not apply substrate presence to location &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string CLEAN_PRESENCE_APPLY_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("CLEAN_PRESENCE_APPLY_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor substrate presence = &apos;{0}&apos;
        ///Forced substrate presence = &apos;{1}&apos;
        ///Do you confirm you wish to force this presence value?.
        /// </summary>
        internal static string CLEAN_PRESENCE_MISMATCH_MESSAGE {
            get {
                return ResourceManager.GetString("CLEAN_PRESENCE_MISMATCH_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch between user input and sensor.
        /// </summary>
        internal static string CLEAN_PRESENCE_MISMATCH_TITLE {
            get {
                return ResourceManager.GetString("CLEAN_PRESENCE_MISMATCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for {0}.
        /// </summary>
        internal static string CLEAN_RESERVED_FOR {
            get {
                return ResourceManager.GetString("CLEAN_RESERVED_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination slot.
        /// </summary>
        internal static string CLEAN_SELECT_DESTINATION_SLOT {
            get {
                return ResourceManager.GetString("CLEAN_SELECT_DESTINATION_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select slot.
        /// </summary>
        internal static string CLEAN_SELECT_SLOT {
            get {
                return ResourceManager.GetString("CLEAN_SELECT_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string CLEAN_SENSOR {
            get {
                return ResourceManager.GetString("CLEAN_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string CLEAN_SIZE {
            get {
                return ResourceManager.GetString("CLEAN_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start clean out.
        /// </summary>
        internal static string CLEAN_START {
            get {
                return ResourceManager.GetString("CLEAN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Input.
        /// </summary>
        internal static string CLEAN_USER_INPUT {
            get {
                return ResourceManager.GetString("CLEAN_USER_INPUT", resourceCulture);
            }
        }
    }
}
