<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{58925a0b-bcf4-4828-885e-2cbd0bc812af}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	
	HardwareControl : HardwareControl;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
HardwareControl();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="192" Count="0" />
      <LineId Id="182" Count="0" />
      <LineId Id="21" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>