//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.EFEM.Brooks.GUI.Views.Panels.Setup.DeviceSettings.Efem.BrooksEfem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrooksEfemSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrooksEfemSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.EFEM.Brooks.GUI.Views.Panels.Setup.DeviceSettings.Efem.BrooksEfem.BrooksE" +
                            "femSettingsResources", typeof(BrooksEfemSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air signal name.
        /// </summary>
        public static string AIR_NODE_SIGNAL {
            get {
                return ResourceManager.GetString("AIR_NODE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks client name.
        /// </summary>
        public static string BROOKS_CLIENT_NAME {
            get {
                return ResourceManager.GetString("BROOKS_CLIENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks DIO name.
        /// </summary>
        public static string BROOKS_DIO_NAME {
            get {
                return ResourceManager.GetString("BROOKS_DIO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks efem name.
        /// </summary>
        public static string BROOKS_EFEM_NAME {
            get {
                return ResourceManager.GetString("BROOKS_EFEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks load port 1 location name.
        /// </summary>
        public static string BROOKS_LOADPORT_1_LOCATION_NAME {
            get {
                return ResourceManager.GetString("BROOKS_LOADPORT_1_LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks load port 2 location name.
        /// </summary>
        public static string BROOKS_LOADPORT_2_LOCATION_NAME {
            get {
                return ResourceManager.GetString("BROOKS_LOADPORT_2_LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks load port 3 location name.
        /// </summary>
        public static string BROOKS_LOADPORT_3_LOCATION_NAME {
            get {
                return ResourceManager.GetString("BROOKS_LOADPORT_3_LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks load port 4 location name.
        /// </summary>
        public static string BROOKS_LOADPORT_4_LOCATION_NAME {
            get {
                return ResourceManager.GetString("BROOKS_LOADPORT_4_LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks process module A location name.
        /// </summary>
        public static string BROOKS_PROCESS_MODULE_A_LOCATION_NAME {
            get {
                return ResourceManager.GetString("BROOKS_PROCESS_MODULE_A_LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks process module B location name.
        /// </summary>
        public static string BROOKS_PROCESS_MODULE_B_LOCATION_NAME {
            get {
                return ResourceManager.GetString("BROOKS_PROCESS_MODULE_B_LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooks process module C location name.
        /// </summary>
        public static string BROOKS_PROCESS_MODULE_C_LOCATION_NAME {
            get {
                return ResourceManager.GetString("BROOKS_PROCESS_MODULE_C_LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door sensor 1 signal name.
        /// </summary>
        public static string DOOR_SENSOR1_NODE_SIGNAL {
            get {
                return ResourceManager.GetString("DOOR_SENSOR1_NODE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door sensor 2 signal name.
        /// </summary>
        public static string DOOR_SENSOR2_NODE_SIGNAL {
            get {
                return ResourceManager.GetString("DOOR_SENSOR2_NODE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlock sensor 1 signal name.
        /// </summary>
        public static string INTLCK_SENSOR1_NODE_SIGNAL {
            get {
                return ResourceManager.GetString("INTLCK_SENSOR1_NODE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlock sensor 2 signal name.
        /// </summary>
        public static string INTLCK_SENSOR2_NODE_SIGNAL {
            get {
                return ResourceManager.GetString("INTLCK_SENSOR2_NODE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure signal name.
        /// </summary>
        public static string PRESSURE_NODE_SIGNAL {
            get {
                return ResourceManager.GetString("PRESSURE_NODE_SIGNAL", resourceCulture);
            }
        }
    }
}
