//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.Maintenance.Wafer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WaferPanelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WaferPanelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.Maintenance.Wafer.WaferPanelResources", typeof(WaferPanelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired ID.
        /// </summary>
        internal static string ACQUIRED_ID {
            get {
                return ResourceManager.GetString("ACQUIRED_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier ID.
        /// </summary>
        internal static string CARRIER_ID {
            get {
                return ResourceManager.GetString("CARRIER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Job ID.
        /// </summary>
        internal static string CONTROLJOB_ID {
            get {
                return ResourceManager.GetString("CONTROLJOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot ID.
        /// </summary>
        internal static string LOT_ID {
            get {
                return ResourceManager.GetString("LOT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Dimension.
        /// </summary>
        internal static string MATERIAL_DIMENSION {
            get {
                return ResourceManager.GetString("MATERIAL_DIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        internal static string MATERIAL_TYPE {
            get {
                return ResourceManager.GetString("MATERIAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation Angle.
        /// </summary>
        internal static string ORIENTATION_ANGLE {
            get {
                return ResourceManager.GetString("ORIENTATION_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Job ID.
        /// </summary>
        internal static string PROCESSJOB_ID {
            get {
                return ResourceManager.GetString("PROCESSJOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Port.
        /// </summary>
        internal static string SOURCE_PORT {
            get {
                return ResourceManager.GetString("SOURCE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Slot.
        /// </summary>
        internal static string SOURCE_SLOT {
            get {
                return ResourceManager.GetString("SOURCE_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrate ID.
        /// </summary>
        internal static string SUBSTRATE_ID {
            get {
                return ResourceManager.GetString("SUBSTRATE_ID", resourceCulture);
            }
        }
    }
}
