//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.Dto
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    
    [DataContract]
    public partial class Available
    {
        [DataMember]
        public int ToolId { get; set; }
        [DataMember]
        public Nullable<int> RecipeId { get; set; }
    
        [DataMember]
        public virtual Recipe Recipe { get; set; }
        [DataMember]
        public virtual Tool Tool { get; set; }
    }
}
