//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.Dto
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    
    [DataContract]
    public partial class ConfigurationData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigurationData()
        {
            this.Chambers = new HashSet<Chamber>();
            this.ConfigurationHistories = new HashSet<ConfigurationHistory>();
            this.ProductConfigurations = new HashSet<ProductConfiguration>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Contents { get; set; }
        [DataMember]
        public Nullable<bool> IsExternal { get; set; }
        [DataMember]
        public int Type { get; set; }
        [DataMember]
        public System.DateTime Created { get; set; }
        [DataMember]
        public System.DateTime Modified { get; set; }
        [DataMember]
        public Nullable<bool> IsArchived { get; set; }
        [DataMember]
        public int CreatorUserId { get; set; }
        [DataMember]
        public byte[] MD5 { get; set; }
        [DataMember]
        public int Version { get; set; }
        [DataMember]
        public int ModifiedByUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Chamber> Chambers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<ConfigurationHistory> ConfigurationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<ProductConfiguration> ProductConfigurations { get; set; }
    }
}
