//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.Dto
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    
    [DataContract]
    public partial class ConfigurationHistory
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public Nullable<int> ConfigurationId { get; set; }
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public string Contents { get; set; }
        [DataMember]
        public int Version { get; set; }
    
        [DataMember]
        public virtual ConfigurationData ConfigurationData { get; set; }
        [DataMember]
        public virtual User User { get; set; }
    }
}
