//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.Dto
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    
    [DataContract]
    public partial class GlobalResultSettings
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int ResultFormat { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public string DataSetting { get; set; }
        [DataMember]
        public string XmlSetting { get; set; }
    }
}
