//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.DataAccess.Dto
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    
    [DataContract]
    public partial class ResultItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultItem()
        {
            this.ResultItemValues = new HashSet<ResultItemValue>();
        }
    
        [DataMember]
        public long Id { get; set; }
        [DataMember]
        public long ResultId { get; set; }
        [DataMember]
        public int ResultType { get; set; }
        [DataMember]
        public string FileName { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public short Idx { get; set; }
        [DataMember]
        public int State { get; set; }
        [DataMember]
        public int InternalState { get; set; }
        [DataMember]
        public Nullable<int> Tag { get; set; }
    
        [DataMember]
        public virtual Result Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<ResultItemValue> ResultItemValues { get; set; }
    }
}
