<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Lightspeed" Id="{b1820b5e-8283-43dc-b399-2d75c16eb6f0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Lightspeed EXTENDS PlcModule
VAR_INPUT
	
	{attribute 'OPC.UA.DA' := '0'}
	LightspeedConfig : LightspeedConfig;
	
	{attribute 'OPC.UA.DA' := '0'}
	LsCalibrateConfig : LsCalibrateConfig;
	
	(* Chamber *)
	Chamber : LightspeedChamber(Config := LightspeedConfig.ChamberConfigs.LightspeedChamberConfig);
		
	(* AttenuationFilterConfigs *) 
	FW212CAttenuationFilter : FW212CAttenuationFilter(Config := LightspeedConfig.AttenuationFilterConfigs.FW212CAttenuationFilterConfig);
	ELL14KAttenuationFilter : ELL14KAttenuationFilter(Config := LightspeedConfig.AttenuationFilterConfigs.ELL14KAttenuationFilterConfig);
	ELL9AttenuationFilter : ELL9AttenuationFilter(Config := LightspeedConfig.AttenuationFilterConfigs.ELL9AttenuationFilterConfig);
	
	(* Slider Attenuation *)
	ELL6SliderAttenuationFilter : ELL6AttenuationFilter(Config := LightspeedConfig.SliderAttenuationFilterConfigs.ELL6SliderFilterConfig);													
	
	(* Rotating switch *) 
	ELL18RotatingSwitch : ELL18AttenuationFilter(Config := LightspeedConfig.RotatingSwitchConfigs.ELL18RotatingSwitchConfig);
	
	(* PolarisationFilterConfigs *) 
	FW212CPolarisationFilter : FW212CPolarisationFilter(Config := LightspeedConfig.PolarisationFilterConfigs.FW212CPolarisationFilterConfig);
	ELL14KPolarisationFilter : ELL14KPolarisationFilter(Config := LightspeedConfig.PolarisationFilterConfigs.ELL14KPolarisationFilterConfig, 
														HsPolarisationConfig := LsCalibrateConfig.HSPowermeter.PolarisationConfig,
														HtPolarisationConfig := LsCalibrateConfig.HTPowermeter.PolarisationConfig);
		
	
	(* LaserConfigs *) 
	SMD12Laser : SMD12Laser(Config := LightspeedConfig.LaserConfigs.SMD12LaserConfig);
	Sapphire488Laser : Sapphire488Laser(Config := LightspeedConfig.LaserConfigs.Sapphire488LaserConfig);
	
	(* FiberSwitchConfigs *) 
	EOLFiberSwitch : EOLFiberSwitch(Config := LightspeedConfig.FiberSwitchConfigs.EOLFiberSwitchConfig);
	
	(* OpticalPowermeterConfigs *) 
	PM101OpticalPowermeterHs : PM101OpticalPowermeterHs(Config := LightspeedConfig.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHs, 
														PolarisationConfig := LsCalibrateConfig.HSPowermeter.PolarisationConfig,
														RFactorSettings := LsCalibrateConfig.HSPowermeter.RFactorSettings,
														ResponsivityConfig := LsCalibrateConfig.HSPowermeter.ResponsivityConfig);
	PM101OpticalPowermeterHt : PM101OpticalPowermeterHt(Config := LightspeedConfig.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHt, 
														PolarisationConfig := LsCalibrateConfig.HTPowermeter.PolarisationConfig, 
														RFactorSettings := LsCalibrateConfig.HTPowermeter.RFactorSettings,
														ResponsivityConfig := LsCalibrateConfig.HTPowermeter.ResponsivityConfig);
	
	(* DistanceSensorConfigs *) 
	MicroEpsilonDistanceSensor : MicroEpsilonDistanceSensor(Config := LightspeedConfig.DistanceSensorConfigs.MicroEpsilonDistanceSensorConfig);
	
	(* MppcConfigs *) 
	C13336MppcWide   : C13336MppcWide(Config := LightspeedConfig.MppcConfigs.C13336MppcConfigWide);
	C13336MppcNarrow : C13366MppcNarrow(Config := LightspeedConfig.MppcConfigs.C13336MppcConfigNarrow);
	
	(* ShutterConfigs *)
	Ed12dssShutter : Ed12dssShutter(Config := LightspeedConfig.ShutterConfigs.Ed12dssShutterConfig);
	Sh10pilShutter : Sh10pilShutter(Config := LightspeedConfig.ShutterConfigs.Sh10pilShutterConfig);
	
	(* FastAttenuationConfigs *)
	Std900FastAttenuation : Std900FastAttenuation(Config := LightspeedConfig.FastAttenuationConfigs.Std900FastAttenuationConfig);	
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
	{attribute 'OPC.UA.DA' := '0'}
	_startCycling : BOOL;
	{attribute 'OPC.UA.DA' := '0'}
	_count : UINT;
	{attribute 'OPC.UA.DA' := '0'}
	_ActivateCyclingMotorOpen : BOOL ; (* 0 = close door ; 1 = open door  *) 
	{attribute 'OPC.UA.DA' := '0'}
	_CyclingCounterReachSetpoint : BOOL ;
	{attribute 'OPC.UA.DA' := '0'}
	OpenCloseCyclingCount : WORD := 10; (* default value *) 
	{attribute 'OPC.UA.DA' := '0'}
	OpenCloseCurrentCounterValue : WORD:= 0; (* init value *)  ;
	{attribute 'OPC.UA.DA' := '0'}
	WaitingTimer : TON;
	{attribute 'OPC.UA.DA' := '0'}
	DoorSlitOpenCloseCounter: CTU;
	{attribute 'OPC.UA.DA' := '0'}
	OpenCloseCyclingCounterReset : BOOL := FALSE; 
	{attribute 'OPC.UA.DA' := '0'}
	_stopCycling: BOOL:= FALSE;	
	
	{attribute 'OPC.UA.DA' := '0'}
	_mppcActivate : BOOL := TRUE; //TODO à remettre 
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
SUPER^();

IF LightspeedConfig.ChamberConfigs.LightspeedChamberConfig.IsEnabled THEN
	Chamber(MppcActivate => _mppcActivate);	
	
	Door_Slit_Ctrl();
	OpenCloseCycling(_startCycling, _count);
	StopCycling(_stopCycling);	
END_IF

(* Attenuation *)
IF LightspeedConfig.AttenuationFilterConfigs.FW212CAttenuationFilterConfig.IsEnabled THEN		
	FW212CAttenuationFilter();
	IF FW212CAttenuationFilter.InitConfigSerialCom THEN
		;
	END_IF
ELSIF LightspeedConfig.AttenuationFilterConfigs.ELL14KAttenuationFilterConfig.IsEnabled THEN		
	ELL14KAttenuationFilter();
	IF ELL14KAttenuationFilter.InitConfigSerialCom THEN
		;
	END_IF
ELSIF LightspeedConfig.AttenuationFilterConfigs.ELL9AttenuationFilterConfig.IsEnabled THEN		
	ELL9AttenuationFilter();
	IF ELL9AttenuationFilter.InitConfigSerialCom THEN
		;
	END_IF		
END_IF

(* Slider Attenuation *)
IF LightspeedConfig.Version = '2' THEN
	IF LightspeedConfig.SliderAttenuationFilterConfigs.ELL6SliderFilterConfig.IsEnabled THEN		
		ELL6SliderAttenuationFilter();
		IF ELL6SliderAttenuationFilter.InitConfigSerialCom THEN
			;
		END_IF
	END_IF
END_IF

(* Rotating switch *)
IF LightspeedConfig.Version = '2' THEN
	IF LightspeedConfig.RotatingSwitchConfigs.ELL18RotatingSwitchConfig.IsEnabled THEN		
		ELL18RotatingSwitch();
		IF ELL18RotatingSwitch.InitConfigSerialCom THEN
			;
		END_IF
	END_IF
END_IF

IF LightspeedConfig.PolarisationFilterConfigs.FW212CPolarisationFilterConfig.IsEnabled THEN
	FW212CPolarisationFilter();	
	IF FW212CPolarisationFilter.InitConfigSerialCom THEN
		;
	END_IF
ELSIF LightspeedConfig.PolarisationFilterConfigs.ELL14KPolarisationFilterConfig.IsEnabled THEN		
	ELL14KPolarisationFilter();
	IF ELL14KPolarisationFilter.InitConfigSerialCom THEN
		;
	END_IF			
END_IF

IF LightspeedConfig.LaserConfigs.SMD12LaserConfig.IsEnabled THEN
	SMD12Laser();
	IF SMD12Laser.InitConfigSerialCom THEN
		;
	END_IF
ELSIF LightspeedConfig.LaserConfigs.Sapphire488LaserConfig.IsEnabled THEN
	Sapphire488Laser();
	IF Sapphire488Laser.InitConfigSerialCom THEN
		;
	END_IF
ELSIF LightspeedConfig.LaserConfigs.Sapphire488LaserConfig.IsEnabled THEN
	Sapphire488Laser();
	IF Sapphire488Laser.InitConfigSerialCom THEN
		;
	END_IF	
END_IF

IF LightspeedConfig.FiberSwitchConfigs.EOLFiberSwitchConfig.IsEnabled THEN
	EOLFiberSwitch();
	IF EOLFiberSwitch.InitConfigSerialCom THEN
		;
	END_IF
END_IF

IF LightspeedConfig.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHs.IsEnabled OR 
   LightspeedConfig.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHs.IsSimulated THEN
	PM101OpticalPowermeterHs(PolarResult := ELL14KPolarisationFilter.PolarResult);
	IF PM101OpticalPowermeterHs.InitConfigSerialCom THEN
		;
	END_IF	
END_IF

IF LightspeedConfig.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHt.IsEnabled THEN
	PM101OpticalPowermeterHt(PolarResult := ELL14KPolarisationFilter.PolarResult);
	IF PM101OpticalPowermeterHt.InitConfigSerialCom THEN
		;
	END_IF	
END_IF

IF LightspeedConfig.DistanceSensorConfigs.MicroEpsilonDistanceSensorConfig.IsEnabled THEN
	MicroEpsilonDistanceSensor();	
END_IF

IF LightspeedConfig.MppcConfigs.C13336MppcConfigWide.IsEnabled THEN
	C13336MppcWide(MppcActivate := _mppcActivate);
	IF C13336MppcWide.InitConfigSerialCom THEN
		;
	END_IF
END_IF

IF LightspeedConfig.MppcConfigs.C13336MppcConfigNarrow.IsEnabled THEN
	C13336MppcNarrow(MppcActivate := _mppcActivate);
	IF C13336MppcNarrow.InitConfigSerialCom THEN
		;
	END_IF
END_IF

IF LightspeedConfig.ShutterConfigs.Ed12dssShutterConfig.IsEnabled THEN
	Ed12dssShutter();	
ELSIF LightspeedConfig.ShutterConfigs.SH10PILShutterConfig.IsEnabled THEN
	Sh10pilShutter();
END_IF

IF LightspeedConfig.FastAttenuationConfigs.Std900FastAttenuationConfig.IsEnabled THEN
	Std900FastAttenuation();	
END_IF
]]></ST>
    </Implementation>
    <Folder Name="DoorSlit" Id="{7e3189a0-bffc-4d7d-8844-3b5c5fe06446}" />
    <Method Name="Door_Slit_Ctrl" Id="{c5558a09-4fa8-46b4-9972-cde4601d6796}" FolderPath="DoorSlit\">
      <Declaration><![CDATA[METHOD Door_Slit_Ctrl : BOOL
VAR_INPUT	
END_VAR
VAR
	timeout : TIME := T#1400MS; (* 2 * open time (700ms)  *) 
	MotorTurnOffAfterTimeout: TON;
END_VAR]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"_CyclingCounterReachSetpoint"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">2</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">130L</v>
                            </o>
                            <o>
                              <v n="Operand">"OpenCloseCyclingCounterReset"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">131L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"CTU"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"DoorSlitOpenCloseCounter"</v>
                            <v n="Type">"CTU"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">121L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"OpenCloseCurrentCounterValue"</v>
                                <v n="Type">"WORD"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">123L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">125L</v>
                              </o>
                              <v n="Id">124L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"OpenCloseCyclingCounterReset"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">127L</v>
                              </o>
                              <v n="Id">126L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"OpenCloseCyclingCount"</v>
                                <v n="Type">"WORD"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">129L</v>
                              </o>
                              <v n="Id">128L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>CU</v>
                              <v>RESET</v>
                              <v>PV</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>WORD</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Q</v>
                              <v>CV</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>WORD</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">122L</v>
                        </o>
                        <v n="Id">132L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">120L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOpen"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">2</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">295L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">289L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"_startCycling"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">292L</v>
                              </o>
                              <v n="Id">291L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"_ActivateCyclingMotorOpen"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">294L</v>
                              </o>
                              <v n="Id">293L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">290L</v>
                        </o>
                        <v n="Id">296L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">288L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOpen"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">3</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">308L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">300L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"_startCycling"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">303L</v>
                              </o>
                              <v n="Id">302L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"_ActivateCyclingMotorOpen"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">1</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">305L</v>
                              </o>
                              <v n="Id">304L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">301L</v>
                        </o>
                        <v n="Id">309L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">299L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">287L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">"Control time out pour Chamber pump down"</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">2</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">180L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">152L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">154L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" />
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeBox">
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">156L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">159L</v>
                                      </o>
                                      <v n="Id">158L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">161L</v>
                                      </o>
                                      <v n="Id">160L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">163L</v>
                                      </o>
                                      <v n="Id">162L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">165L</v>
                                      </o>
                                      <v n="Id">164L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">157L</v>
                                </o>
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">166L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">169L</v>
                                      </o>
                                      <v n="Id">168L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">171L</v>
                                      </o>
                                      <v n="Id">170L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">173L</v>
                                      </o>
                                      <v n="Id">172L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputArmNotExtended"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">175L</v>
                                      </o>
                                      <v n="Id">174L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">177L</v>
                                      </o>
                                      <v n="Id">176L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">167L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <n n="EN" />
                              <n n="ENO" />
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">155L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">1</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">179L</v>
                              </o>
                              <v n="Id">178L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">153L</v>
                        </o>
                        <v n="Id">181L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">151L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">"Control time out pour Chamber pump down"</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">3</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">209L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">183L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">185L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" />
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeBox">
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">187L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">190L</v>
                                      </o>
                                      <v n="Id">189L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">192L</v>
                                      </o>
                                      <v n="Id">191L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">194L</v>
                                      </o>
                                      <v n="Id">193L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">196L</v>
                                      </o>
                                      <v n="Id">195L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">188L</v>
                                </o>
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">197L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">200L</v>
                                      </o>
                                      <v n="Id">199L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">202L</v>
                                      </o>
                                      <v n="Id">201L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">204L</v>
                                      </o>
                                      <v n="Id">203L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">206L</v>
                                      </o>
                                      <v n="Id">205L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">198L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <n n="EN" />
                              <n n="ENO" />
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">186L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">208L</v>
                              </o>
                              <v n="Id">207L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">184L</v>
                        </o>
                        <v n="Id">210L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">182L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">2</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">240L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">212L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">214L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" />
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeBox">
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">216L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_ActivateCyclingMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">219L</v>
                                      </o>
                                      <v n="Id">218L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">221L</v>
                                      </o>
                                      <v n="Id">220L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">223L</v>
                                      </o>
                                      <v n="Id">222L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">225L</v>
                                      </o>
                                      <v n="Id">224L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">217L</v>
                                </o>
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">226L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_ActivateCyclingMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">229L</v>
                                      </o>
                                      <v n="Id">228L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">231L</v>
                                      </o>
                                      <v n="Id">230L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">233L</v>
                                      </o>
                                      <v n="Id">232L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputArmNotExtended"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">235L</v>
                                      </o>
                                      <v n="Id">234L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">237L</v>
                                      </o>
                                      <v n="Id">236L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">227L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <n n="EN" />
                              <n n="ENO" />
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">215L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">1</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">239L</v>
                              </o>
                              <v n="Id">238L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">213L</v>
                        </o>
                        <v n="Id">241L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">211L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">3</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">269L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">243L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">245L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" />
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeBox">
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">247L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_ActivateCyclingMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">250L</v>
                                      </o>
                                      <v n="Id">249L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">252L</v>
                                      </o>
                                      <v n="Id">251L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">254L</v>
                                      </o>
                                      <v n="Id">253L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">256L</v>
                                      </o>
                                      <v n="Id">255L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">248L</v>
                                </o>
                                <o>
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">257L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_ActivateCyclingMotorOpen"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">260L</v>
                                      </o>
                                      <v n="Id">259L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitClosed"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">262L</v>
                                      </o>
                                      <v n="Id">261L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"Chamber.IoLightspeed.InputDoorslitOpened"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">264L</v>
                                      </o>
                                      <v n="Id">263L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_startCycling"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">266L</v>
                                      </o>
                                      <v n="Id">265L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">258L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <n n="EN" />
                              <n n="ENO" />
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">246L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">268L</v>
                              </o>
                              <v n="Id">267L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">244L</v>
                        </o>
                        <v n="Id">270L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">242L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">3</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">279L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"TON"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"MotorTurnOffAfterTimeout"</v>
                            <v n="Type">"TON"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">272L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">274L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Chamber.IoLightspeed.OutputDoorslitMotorOn"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">276L</v>
                              </o>
                              <v n="Id">275L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"timeout"</v>
                                <v n="Type">"TIME"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">278L</v>
                              </o>
                              <v n="Id">277L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>IN</v>
                              <v>PT</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Q</v>
                              <v>ET</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">273L</v>
                        </o>
                        <v n="Id">280L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">271L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{09564059-546a-497c-9b54-4b93903ae9de}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	Config : LightspeedConfig;
	CalibrateConfig : LsCalibrateConfig;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[LightspeedConfig := Config;
LsCalibrateConfig := CalibrateConfig;
LsBkgrdLsSerialCom(Config := LightspeedConfig);

IF Config.IsEnabled THEN
	_logger.Information('Lightspeed devices initialization starting...');
END_IF	

(* Chamber *)
IF Config.ChamberConfigs.LightspeedChamberConfig.IsEnabled THEN
	Chamber.FB_init(FALSE, FALSE, Config := Config.ChamberConfigs.LightspeedChamberConfig);	
END_IF

(* AttenuationFilterConfigs *)
IF Config.AttenuationFilterConfigs.FW212CAttenuationFilterConfig.IsEnabled THEN
	FW212CAttenuationFilter.FB_init(FALSE, FALSE, Config := Config.AttenuationFilterConfigs.FW212CAttenuationFilterConfig);	
ELSIF Config.AttenuationFilterConfigs.ELL14KAttenuationFilterConfig.IsEnabled THEN
	ELL14KAttenuationFilter.FB_init(FALSE, FALSE, Config := Config.AttenuationFilterConfigs.ELL14KAttenuationFilterConfig);
END_IF

(* Slider Attenuation *)
IF Config.Version = '2' THEN
	IF Config.SliderAttenuationFilterConfigs.ELL6SliderFilterConfig.IsEnabled THEN
		ELL6SliderAttenuationFilter.FB_init(FALSE, FALSE, Config := Config.SliderAttenuationFilterConfigs.ELL6SliderFilterConfig);
	END_IF
END_IF

(* Rotating switch *)
IF Config.Version = '2' THEN
	IF Config.RotatingSwitchConfigs.ELL18RotatingSwitchConfig.IsEnabled THEN
		ELL18RotatingSwitch.FB_init(FALSE, FALSE, Config := Config.RotatingSwitchConfigs.ELL18RotatingSwitchConfig);
	END_IF
END_IF

(* PolarisationFilterConfigs *)
IF Config.PolarisationFilterConfigs.FW212CPolarisationFilterConfig.IsEnabled THEN
	FW212CPolarisationFilter.FB_init(FALSE, FALSE, Config := Config.PolarisationFilterConfigs.FW212CPolarisationFilterConfig);	
ELSIF Config.PolarisationFilterConfigs.ELL14KPolarisationFilterConfig.IsEnabled THEN
	ELL14KPolarisationFilter.FB_init(FALSE, FALSE, Config := Config.PolarisationFilterConfigs.ELL14KPolarisationFilterConfig, 
												   HsPolarisationConfig := CalibrateConfig.HSPowermeter.PolarisationConfig,
												   HtPolarisationConfig := CalibrateConfig.HTPowermeter.PolarisationConfig);
END_IF

(* LaserConfigs *) 
IF Config.LaserConfigs.SMD12LaserConfig.IsEnabled THEN
	SMD12Laser.FB_init(FALSE, FALSE, Config := Config.LaserConfigs.SMD12LaserConfig);	
ELSIF Config.LaserConfigs.Sapphire488LaserConfig.IsEnabled THEN
	Sapphire488Laser.FB_init(FALSE, FALSE, Config := Config.LaserConfigs.Sapphire488LaserConfig);	
END_IF

(* FiberSwitchConfigs *) 
IF Config.FiberSwitchConfigs.EOLFiberSwitchConfig.IsEnabled THEN
	EOLFiberSwitch.FB_init(FALSE, FALSE, Config := Config.FiberSwitchConfigs.EOLFiberSwitchConfig);	
END_IF

(* OpticalPowermeterConfigs *) 
IF Config.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHs.IsEnabled THEN
	PM101OpticalPowermeterHs.FB_init(FALSE, FALSE, Config := Config.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHs, 
												   PolarisationConfig := CalibrateConfig.HSPowermeter.PolarisationConfig, 
												   RFactorSettings := CalibrateConfig.HSPowermeter.RFactorSettings,
												   ResponsivityConfig := CalibrateConfig.HSPowermeter.ResponsivityConfig);		
END_IF
IF Config.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHt.IsEnabled THEN
	PM101OpticalPowermeterHt.FB_init(FALSE, FALSE, Config := Config.OpticalPowermeterConfigs.PM101OpticalPowermeterConfigHt, 
												   PolarisationConfig := CalibrateConfig.HTPowermeter.PolarisationConfig,
												   RFactorSettings := CalibrateConfig.HTPowermeter.RFactorSettings,
												   ResponsivityConfig := CalibrateConfig.HTPowermeter.ResponsivityConfig);
END_IF

(* DistanceSensorConfigs *) 
IF Config.DistanceSensorConfigs.MicroEpsilonDistanceSensorConfig.IsEnabled THEN
	MicroEpsilonDistanceSensor.FB_init(FALSE, FALSE, Config := Config.DistanceSensorConfigs.MicroEpsilonDistanceSensorConfig);	
END_IF

(* MppcConfigs *) 
IF Config.MppcConfigs.C13336MppcConfigWide.IsEnabled THEN
	C13336MppcWide.FB_init(FALSE, FALSE, Config := Config.MppcConfigs.C13336MppcConfigWide);	
END_IF
IF Config.MppcConfigs.C13336MppcConfigNarrow.IsEnabled THEN
	C13336MppcNarrow.FB_init(FALSE, FALSE, Config := Config.MppcConfigs.C13336MppcConfigNarrow);	
END_IF

(* ShutterConfigs *) 
IF Config.ShutterConfigs.Ed12dssShutterConfig.IsEnabled THEN
	Ed12dssShutter.FB_init(FALSE, FALSE, Config := Config.ShutterConfigs.Ed12dssShutterConfig);	
ELSIF Config.ShutterConfigs.SH10PILShutterConfig.IsEnabled THEN
	Sh10pilShutter.FB_init(FALSE, FALSE, Config := Config.ShutterConfigs.SH10PILShutterConfig);	
END_IF

IF Config.IsEnabled THEN
	_logger.Information('Lightspeed devices initialization ended...');
END_IF	]]></ST>
      </Implementation>
    </Method>
    <Method Name="OpenCloseCycling" Id="{8a380f41-0443-4c66-a6ce-51982bdb92a2}" FolderPath="DoorSlit\">
      <Declaration><![CDATA[METHOD OpenCloseCycling : BOOL
VAR_INPUT
	Execute : BOOL;
	Count : UINT;
END_VAR
VAR 
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF Execute THEN
	(* timer pour l'enchainement des open/close *)
	(* WaitingTimer.in := TRUE;
	WaitingTimer.PT := T#4S;*)
	WaitingTimer (IN :=TRUE , PT := T#5S,Q=>, ET=> );
	
	(* WaitingTimer.Q is TRUE, PT seconds after IN had a rising edge *)
	IF WaitingTimer.Q THEN
		(* RAZ du timer *)
		WaitingTimer (IN := FALSE);
		(* coupe le motor ON par securité*)
		Chamber.IoLightspeed.OutputDoorslitMotorOn := FALSE;
		(* MAJ du compteur*)
		OpenCloseCyclingCount := Count;
		(* porte ouverte => on demande la fermeture*)
		IF (_CyclingCounterReachSetpoint) THEN
			(* arret du cycling et re init des variables*)
			Chamber.IoLightspeed.OutputDoorslitMotorOn := FALSE;
			_startCycling := FALSE;
			_CyclingCounterReachSetpoint := FALSE;
			_ActivateCyclingMotorOpen := FALSE;
			OpenCloseCycling := FALSE;
			OpenCloseCurrentCounterValue := 0;
			(* to do lever un timeout vers acquisition si not(_CyclingCounterReachSetpoint) => pb d'open/close  *)
		ELSIF Chamber.IoLightspeed.InputDoorslitOpened THEN
			_ActivateCyclingMotorOpen := FALSE;	
		(* porte fermée => on demande l'ouverture *)			
		ELSIF (Chamber.IoLightspeed.InputDoorslitClosed) THEN
			_ActivateCyclingMotorOpen := TRUE;	
		END_IF
	END_IF
END_IF


]]></ST>
      </Implementation>
    </Method>
    <Method Name="StopCycling" Id="{74208cd1-90d0-4c46-8202-5e5729222b64}" FolderPath="DoorSlit\">
      <Declaration><![CDATA[METHOD StopCycling : BOOL
VAR_INPUT
	Execute : BOOL;
END_VAR
VAR 
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF Execute THEN
	(* stop du cycling*)
	(* on attend le porte fermée pour arreter le cycling *)
	IF ( NOT (Chamber.IoLightspeed.InputDoorslitOpened) AND Chamber.IoLightspeed.InputDoorslitClosed)  THEN
		(* arret du cycling et re init des variables*)
		(* arret du cycling *)
		_startCycling := FALSE;
		(* coupe le moteur par securité *)
		Chamber.IoLightspeed.OutputDoorslitMotorOn := FALSE;
		(* fin du stop cycling*)
		_stopCycling:= FALSE;
		(* re init du compteur de cycle *)
		_CyclingCounterReachSetpoint := FALSE;
		OpenCloseCurrentCounterValue := 0;
		OpenCloseCyclingCount := 0;
	END_IF
END_IF


]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Lightspeed">
      <LineId Id="1928" Count="0" />
      <LineId Id="1927" Count="0" />
      <LineId Id="365" Count="1" />
      <LineId Id="1079" Count="0" />
      <LineId Id="1078" Count="0" />
      <LineId Id="1004" Count="1" />
      <LineId Id="369" Count="1" />
      <LineId Id="1418" Count="0" />
      <LineId Id="371" Count="3" />
      <LineId Id="826" Count="0" />
      <LineId Id="376" Count="0" />
      <LineId Id="496" Count="1" />
      <LineId Id="499" Count="0" />
      <LineId Id="833" Count="0" />
      <LineId Id="494" Count="0" />
      <LineId Id="377" Count="5" />
      <LineId Id="1419" Count="1" />
      <LineId Id="1555" Count="0" />
      <LineId Id="1425" Count="3" />
      <LineId Id="383" Count="0" />
      <LineId Id="1429" Count="0" />
      <LineId Id="1556" Count="0" />
      <LineId Id="1431" Count="0" />
      <LineId Id="1433" Count="0" />
      <LineId Id="1557" Count="0" />
      <LineId Id="1434" Count="4" />
      <LineId Id="1432" Count="0" />
      <LineId Id="1558" Count="0" />
      <LineId Id="1430" Count="0" />
      <LineId Id="541" Count="3" />
      <LineId Id="539" Count="0" />
      <LineId Id="384" Count="11" />
      <LineId Id="1795" Count="3" />
      <LineId Id="1794" Count="0" />
      <LineId Id="396" Count="4" />
      <LineId Id="827" Count="2" />
      <LineId Id="800" Count="0" />
      <LineId Id="405" Count="0" />
      <LineId Id="1675" Count="0" />
      <LineId Id="810" Count="1" />
      <LineId Id="830" Count="2" />
      <LineId Id="822" Count="0" />
      <LineId Id="809" Count="0" />
      <LineId Id="406" Count="10" />
      <LineId Id="928" Count="5" />
      <LineId Id="927" Count="0" />
      <LineId Id="645" Count="2" />
      <LineId Id="644" Count="0" />
      <LineId Id="694" Count="3" />
      <LineId Id="1300" Count="1" />
      <LineId Id="698" Count="1" />
      <LineId Id="586" Count="0" />
      <LineId Id="324" Count="0" />
      <LineId Id="102" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="126" Count="3" />
      <LineId Id="1929" Count="0" />
    </LineIds>
    <LineIds Name="Lightspeed.FB_init">
      <LineId Id="172" Count="18" />
      <LineId Id="251" Count="1" />
      <LineId Id="269" Count="0" />
      <LineId Id="255" Count="1" />
      <LineId Id="250" Count="0" />
      <LineId Id="270" Count="0" />
      <LineId Id="257" Count="0" />
      <LineId Id="259" Count="0" />
      <LineId Id="271" Count="0" />
      <LineId Id="260" Count="1" />
      <LineId Id="258" Count="0" />
      <LineId Id="272" Count="0" />
      <LineId Id="191" Count="12" />
      <LineId Id="301" Count="0" />
      <LineId Id="300" Count="0" />
      <LineId Id="204" Count="11" />
      <LineId Id="280" Count="0" />
      <LineId Id="216" Count="4" />
      <LineId Id="281" Count="0" />
      <LineId Id="221" Count="17" />
      <LineId Id="289" Count="0" />
      <LineId Id="292" Count="0" />
      <LineId Id="239" Count="3" />
      <LineId Id="19" Count="0" />
    </LineIds>
    <LineIds Name="Lightspeed.OpenCloseCycling">
      <LineId Id="130" Count="1" />
      <LineId Id="174" Count="0" />
      <LineId Id="196" Count="0" />
      <LineId Id="175" Count="0" />
      <LineId Id="180" Count="0" />
      <LineId Id="137" Count="0" />
      <LineId Id="140" Count="2" />
      <LineId Id="177" Count="0" />
      <LineId Id="176" Count="0" />
      <LineId Id="143" Count="2" />
      <LineId Id="198" Count="7" />
      <LineId Id="197" Count="0" />
      <LineId Id="146" Count="4" />
      <LineId Id="160" Count="4" />
      <LineId Id="22" Count="0" />
    </LineIds>
    <LineIds Name="Lightspeed.StopCycling">
      <LineId Id="130" Count="0" />
      <LineId Id="231" Count="0" />
      <LineId Id="236" Count="0" />
      <LineId Id="259" Count="0" />
      <LineId Id="284" Count="1" />
      <LineId Id="260" Count="0" />
      <LineId Id="283" Count="0" />
      <LineId Id="261" Count="0" />
      <LineId Id="265" Count="1" />
      <LineId Id="287" Count="2" />
      <LineId Id="286" Count="0" />
      <LineId Id="235" Count="0" />
      <LineId Id="162" Count="2" />
      <LineId Id="22" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>