//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.Gem.EPT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EPTRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EPTRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.Gem.EPT.EPTRessources", typeof(EPTRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked reason.
        /// </summary>
        internal static string EPT_BLOCKED_REASON {
            get {
                return ResourceManager.GetString("EPT_BLOCKED_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked reason text.
        /// </summary>
        internal static string EPT_BLOCKED_REASON_TEXT {
            get {
                return ResourceManager.GetString("EPT_BLOCKED_REASON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name.
        /// </summary>
        internal static string EPT_ELEMENT_NAME {
            get {
                return ResourceManager.GetString("EPT_ELEMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type.
        /// </summary>
        internal static string EPT_ELEMENT_TYPE {
            get {
                return ResourceManager.GetString("EPT_ELEMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous state.
        /// </summary>
        internal static string EPT_PREVIOUS_STATE {
            get {
                return ResourceManager.GetString("EPT_PREVIOUS_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous task name.
        /// </summary>
        internal static string EPT_PREVIOUS_TASK_NAME {
            get {
                return ResourceManager.GetString("EPT_PREVIOUS_TASK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous task type.
        /// </summary>
        internal static string EPT_PREVIOUS_TASK_TYPE {
            get {
                return ResourceManager.GetString("EPT_PREVIOUS_TASK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string EPT_STATE {
            get {
                return ResourceManager.GetString("EPT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Time.
        /// </summary>
        internal static string EPT_STATE_TIME {
            get {
                return ResourceManager.GetString("EPT_STATE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPT Spy.
        /// </summary>
        internal static string EPT_TAB_TITLE {
            get {
                return ResourceManager.GetString("EPT_TAB_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        internal static string EPT_TASK_NAME {
            get {
                return ResourceManager.GetString("EPT_TASK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task type.
        /// </summary>
        internal static string EPT_TASK_TYPE {
            get {
                return ResourceManager.GetString("EPT_TASK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackers.
        /// </summary>
        internal static string EPT_TITLE {
            get {
                return ResourceManager.GetString("EPT_TITLE", resourceCulture);
            }
        }
    }
}
