//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.UTO.Controller.Views.Panels.Gem.SubstrateTracking {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubstrateTrackingRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubstrateTrackingRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.UTO.Controller.Views.Panels.Gem.SubstrateTracking.SubstrateTrackingRessou" +
                            "rces", typeof(SubstrateTrackingRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafers tracking.
        /// </summary>
        internal static string SUB_TRACK {
            get {
                return ResourceManager.GetString("SUB_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired ID.
        /// </summary>
        internal static string SUB_TRACK_ACQUIRED_ID {
            get {
                return ResourceManager.GetString("SUB_TRACK_ACQUIRED_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare histories.
        /// </summary>
        internal static string SUB_TRACK_COMPARE {
            get {
                return ResourceManager.GetString("SUB_TRACK_COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string SUB_TRACK_DESTINATION {
            get {
                return ResourceManager.GetString("SUB_TRACK_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorten long times display.
        /// </summary>
        internal static string SUB_TRACK_DISPLAY_GAP {
            get {
                return ResourceManager.GetString("SUB_TRACK_DISPLAY_GAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string SUB_TRACK_END {
            get {
                return ResourceManager.GetString("SUB_TRACK_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is on location.
        /// </summary>
        internal static string SUB_TRACK_FILTER_LOCID {
            get {
                return ResourceManager.GetString("SUB_TRACK_FILTER_LOCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string SUB_TRACK_FILTER_PERIOD {
            get {
                return ResourceManager.GetString("SUB_TRACK_FILTER_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Went by location.
        /// </summary>
        internal static string SUB_TRACK_FILTER_WENTBY_LOC {
            get {
                return ResourceManager.GetString("SUB_TRACK_FILTER_WENTBY_LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string SUB_TRACK_HISTORY {
            get {
                return ResourceManager.GetString("SUB_TRACK_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        internal static string SUB_TRACK_HOUR {
            get {
                return ResourceManager.GetString("SUB_TRACK_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string SUB_TRACK_ID {
            get {
                return ResourceManager.GetString("SUB_TRACK_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string SUB_TRACK_LOCATION {
            get {
                return ResourceManager.GetString("SUB_TRACK_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string SUB_TRACK_LOCATIONS {
            get {
                return ResourceManager.GetString("SUB_TRACK_LOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot ID.
        /// </summary>
        internal static string SUB_TRACK_LOT_ID {
            get {
                return ResourceManager.GetString("SUB_TRACK_LOT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min(s).
        /// </summary>
        internal static string SUB_TRACK_MIN {
            get {
                return ResourceManager.GetString("SUB_TRACK_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string SUB_TRACK_POSITION {
            get {
                return ResourceManager.GetString("SUB_TRACK_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process state.
        /// </summary>
        internal static string SUB_TRACK_PROC_STATE {
            get {
                return ResourceManager.GetString("SUB_TRACK_PROC_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec(s).
        /// </summary>
        internal static string SUB_TRACK_SECOND {
            get {
                return ResourceManager.GetString("SUB_TRACK_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SUB_TRACK_SELECT_ALL {
            get {
                return ResourceManager.GetString("SUB_TRACK_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select wafers to compare.
        /// </summary>
        internal static string SUB_TRACK_SELECT_SUB {
            get {
                return ResourceManager.GetString("SUB_TRACK_SELECT_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SUB_TRACK_SOURCE {
            get {
                return ResourceManager.GetString("SUB_TRACK_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string SUB_TRACK_START {
            get {
                return ResourceManager.GetString("SUB_TRACK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SUB_TRACK_STATE {
            get {
                return ResourceManager.GetString("SUB_TRACK_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID status.
        /// </summary>
        internal static string SUB_TRACK_SUBST_ID_STATUS {
            get {
                return ResourceManager.GetString("SUB_TRACK_SUBST_ID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafers.
        /// </summary>
        internal static string SUB_TRACK_SUBSTRATES {
            get {
                return ResourceManager.GetString("SUB_TRACK_SUBSTRATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string SUB_TRACK_TOTAL {
            get {
                return ResourceManager.GetString("SUB_TRACK_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SUB_TRACK_TYPE {
            get {
                return ResourceManager.GetString("SUB_TRACK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        internal static string SUB_TRACK_UNSELECT_ALL {
            get {
                return ResourceManager.GetString("SUB_TRACK_UNSELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string SUB_TRACK_USAGE {
            get {
                return ResourceManager.GetString("SUB_TRACK_USAGE", resourceCulture);
            }
        }
    }
}
