//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.PM.ANA.Client.CommonUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.PM.ANA.Client.CommonUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average in area.
        /// </summary>
        public static string AverageInArea {
            get {
                return ResourceManager.GetString("AverageInArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central.
        /// </summary>
        public static string Central {
            get {
                return ResourceManager.GetString("Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elipse.
        /// </summary>
        public static string Elipse {
            get {
                return ResourceManager.GetString("Elipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lise.
        /// </summary>
        public static string Lise {
            get {
                return ResourceManager.GetString("Lise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lise and Camera.
        /// </summary>
        public static string LiseAndCamera {
            get {
                return ResourceManager.GetString("LiseAndCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        public static string MeasureDescriptionBow {
            get {
                return ResourceManager.GetString("MeasureDescriptionBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement of the wafer edge trim.
        /// </summary>
        public static string MeasureDescriptionEdgeTrim {
            get {
                return ResourceManager.GetString("MeasureDescriptionEdgeTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region measurement of Nano Topography(3D).
        /// </summary>
        public static string MeasureDescriptionNanoTopo {
            get {
                return ResourceManager.GetString("MeasureDescriptionNanoTopo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponctual measurement of layers thickness .
        /// </summary>
        public static string MeasureDescriptionThickness {
            get {
                return ResourceManager.GetString("MeasureDescriptionThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region measurement of Topography(3D).
        /// </summary>
        public static string MeasureDescriptionTopography {
            get {
                return ResourceManager.GetString("MeasureDescriptionTopography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponctual measurement of a Trench width and depth.
        /// </summary>
        public static string MeasureDescriptionTrench {
            get {
                return ResourceManager.GetString("MeasureDescriptionTrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponctual measurement of a TSV depth and measurement of diameters of the TSVs.
        /// </summary>
        public static string MeasureDescriptionTSV {
            get {
                return ResourceManager.GetString("MeasureDescriptionTSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement of the wafer warp and total thickness variation.
        /// </summary>
        public static string MeasureDescriptionWarp {
            get {
                return ResourceManager.GetString("MeasureDescriptionWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        public static string MeasureNameBow {
            get {
                return ResourceManager.GetString("MeasureNameBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Trim.
        /// </summary>
        public static string MeasureNameEdgeTrim {
            get {
                return ResourceManager.GetString("MeasureNameEdgeTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nano Topo - 3D.
        /// </summary>
        public static string MeasureNameNanoTopo {
            get {
                return ResourceManager.GetString("MeasureNameNanoTopo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string MeasureNameThickness {
            get {
                return ResourceManager.GetString("MeasureNameThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topography - 3D.
        /// </summary>
        public static string MeasureNameTopography {
            get {
                return ResourceManager.GetString("MeasureNameTopography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trench.
        /// </summary>
        public static string MeasureNameTrench {
            get {
                return ResourceManager.GetString("MeasureNameTrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSV.
        /// </summary>
        public static string MeasureNameTSV {
            get {
                return ResourceManager.GetString("MeasureNameTSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp.
        /// </summary>
        public static string MeasureNameWarp {
            get {
                return ResourceManager.GetString("MeasureNameWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized.
        /// </summary>
        public static string Optimized {
            get {
                return ResourceManager.GetString("Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per foup.
        /// </summary>
        public static string PerFoup {
            get {
                return ResourceManager.GetString("PerFoup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per measurement type.
        /// </summary>
        public static string PerMeasurementType {
            get {
                return ResourceManager.GetString("PerMeasurementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per point.
        /// </summary>
        public static string PerPoint {
            get {
                return ResourceManager.GetString("PerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per wafer.
        /// </summary>
        public static string PerWafer {
            get {
                return ResourceManager.GetString("PerWafer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuck center.
        /// </summary>
        public static string PositionChuckCenter {
            get {
                return ResourceManager.GetString("PositionChuckCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PositionHome {
            get {
                return ResourceManager.GetString("PositionHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual load.
        /// </summary>
        public static string PositionManualLoad {
            get {
                return ResourceManager.GetString("PositionManualLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        public static string PositionPark {
            get {
                return ResourceManager.GetString("PositionPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafer center.
        /// </summary>
        public static string PositionWaferCenter {
            get {
                return ResourceManager.GetString("PositionWaferCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
    }
}
