//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.EFEM.Controller.Views.TitlePanel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitlePanelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitlePanelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.EFEM.Controller.Views.TitlePanel.TitlePanelResources", typeof(TitlePanelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFEM.
        /// </summary>
        public static string TITLE_EFEM {
            get {
                return ResourceManager.GetString("TITLE_EFEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string TITLE_PANEL_AIR {
            get {
                return ResourceManager.GetString("TITLE_PANEL_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner.
        /// </summary>
        public static string TITLE_PANEL_ALIGNER {
            get {
                return ResourceManager.GetString("TITLE_PANEL_ALIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Communication State.
        /// </summary>
        public static string TITLE_PANEL_COMMUNICATION_COMMAND {
            get {
                return ResourceManager.GetString("TITLE_PANEL_COMMUNICATION_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Control State.
        /// </summary>
        public static string TITLE_PANEL_CONTROL_COMMAND {
            get {
                return ResourceManager.GetString("TITLE_PANEL_CONTROL_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Equipment State.
        /// </summary>
        public static string TITLE_PANEL_EQUIPMENT_COMMAND {
            get {
                return ResourceManager.GetString("TITLE_PANEL_EQUIPMENT_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFU.
        /// </summary>
        public static string TITLE_PANEL_FFU {
            get {
                return ResourceManager.GetString("TITLE_PANEL_FFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string TITLE_PANEL_GEM_COMM {
            get {
                return ResourceManager.GetString("TITLE_PANEL_GEM_COMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEM commands.
        /// </summary>
        public static string TITLE_PANEL_GEM_COMMANDS {
            get {
                return ResourceManager.GetString("TITLE_PANEL_GEM_COMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string TITLE_PANEL_GEM_CONNECTION {
            get {
                return ResourceManager.GetString("TITLE_PANEL_GEM_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string TITLE_PANEL_GEM_CONTROL {
            get {
                return ResourceManager.GetString("TITLE_PANEL_GEM_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Connection.
        /// </summary>
        public static string TITLE_PANEL_HARDWARE_CONNECTION {
            get {
                return ResourceManager.GetString("TITLE_PANEL_HARDWARE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string TITLE_PANEL_HOST {
            get {
                return ResourceManager.GetString("TITLE_PANEL_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadPort.
        /// </summary>
        public static string TITLE_PANEL_LP {
            get {
                return ResourceManager.GetString("TITLE_PANEL_LP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadPort 1.
        /// </summary>
        public static string TITLE_PANEL_LP1 {
            get {
                return ResourceManager.GetString("TITLE_PANEL_LP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadPort 2.
        /// </summary>
        public static string TITLE_PANEL_LP2 {
            get {
                return ResourceManager.GetString("TITLE_PANEL_LP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadPort 3.
        /// </summary>
        public static string TITLE_PANEL_LP3 {
            get {
                return ResourceManager.GetString("TITLE_PANEL_LP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadPort 4.
        /// </summary>
        public static string TITLE_PANEL_LP4 {
            get {
                return ResourceManager.GetString("TITLE_PANEL_LP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string TITLE_PANEL_MODE {
            get {
                return ResourceManager.GetString("TITLE_PANEL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string TITLE_PANEL_PM {
            get {
                return ResourceManager.GetString("TITLE_PANEL_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM1.
        /// </summary>
        public static string TITLE_PANEL_PM1 {
            get {
                return ResourceManager.GetString("TITLE_PANEL_PM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM2.
        /// </summary>
        public static string TITLE_PANEL_PM2 {
            get {
                return ResourceManager.GetString("TITLE_PANEL_PM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing State.
        /// </summary>
        public static string TITLE_PANEL_PROCESSING_STATE {
            get {
                return ResourceManager.GetString("TITLE_PANEL_PROCESSING_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot.
        /// </summary>
        public static string TITLE_PANEL_ROBOT {
            get {
                return ResourceManager.GetString("TITLE_PANEL_ROBOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string TITLE_PANEL_SAFETYDOOR {
            get {
                return ResourceManager.GetString("TITLE_PANEL_SAFETYDOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string TITLE_PANEL_SUBSTRATEREADER {
            get {
                return ResourceManager.GetString("TITLE_PANEL_SUBSTRATEREADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum.
        /// </summary>
        public static string TITLE_PANEL_VACUUM {
            get {
                return ResourceManager.GetString("TITLE_PANEL_VACUUM", resourceCulture);
            }
        }
    }
}
