//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitySC.Equipment.Devices.Controller.OperatingModeSM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControllerOperatingModeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerOperatingModeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitySC.Equipment.Devices.Controller.OperatingModeSM.ControllerOperatingModeResou" +
                            "rces", typeof(ControllerOperatingModeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All load ports are out of service.
        /// </summary>
        internal static string ERROR_ALL_LP_OUT_OF_SERVICE {
            get {
                return ResourceManager.GetString("ERROR_ALL_LP_OUT_OF_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All process modules are out of service.
        /// </summary>
        internal static string ERROR_ALL_PM_OUT_OF_SERVICE {
            get {
                return ResourceManager.GetString("ERROR_ALL_PM_OUT_OF_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device(s) in maintenance: .
        /// </summary>
        internal static string ERROR_DEVICE_IN_MAINTENANCE {
            get {
                return ResourceManager.GetString("ERROR_DEVICE_IN_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device(s) not communicating: .
        /// </summary>
        internal static string ERROR_DEVICE_NOT_COMMUNICATING {
            get {
                return ResourceManager.GetString("ERROR_DEVICE_NOT_COMMUNICATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode requested.
        /// </summary>
        internal static string ERROR_MANUAL_MODE_REQUESTED {
            get {
                return ResourceManager.GetString("ERROR_MANUAL_MODE_REQUESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred on controller.
        /// </summary>
        internal static string ERROR_OCCURRED {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A process module used by a job is out of service.
        /// </summary>
        internal static string ERROR_PM_OUT_OF_SERVICE_DURING_JOB {
            get {
                return ResourceManager.GetString("ERROR_PM_OUT_OF_SERVICE_DURING_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wafer(s) still present in the machine.
        /// </summary>
        internal static string ERROR_WAFER_PRESENT {
            get {
                return ResourceManager.GetString("ERROR_WAFER_PRESENT", resourceCulture);
            }
        }
    }
}
